// NIFTY 100 — current 100-symbol universe used by the scanner.
// Symbols are NSE trading symbols; no .NS suffix.
// Keep this file at exactly 100 unique constituents.

module.exports = [
    // NIFTY 50
    "HDFCBANK","ICICIBANK","RELIANCE","BHARTIARTL","LT","SBIN","INFY","AXISBANK","M&M","BAJFINANCE",
    "KOTAKBANK","ITC","TCS","ETERNAL","TITAN","SUNPHARMA","HINDUNILVR","MARUTI","NTPC","SHRIRAMFIN",
    "TATASTEEL","HINDALCO","BEL","HCLTECH","ULTRACEMCO","BAJAJ-AUTO","ADANIPORTS","GRASIM","ASIANPAINT","POWERGRID",
    "INDIGO","JSWSTEEL","BAJAJFINSV","EICHERMOT","NESTLEIND","TECHM","TRENT","COALINDIA","ONGC","APOLLOHOSP",
    "ADANIENT","JIOFIN","CIPLA","SBILIFE","MAXHEALTH","DRREDDY","TATACONSUM","TMPV","HDFCLIFE","WIPRO",

    // NIFTY NEXT 50
    "DIVISLAB","TVSMOTOR","TMCV","HAL","ADANIPOWER","CHOLAFIN","TORNTPHARM","CUMMINSIND","MOTHERSON","INDHOTEL",
    "ABB","ADANIENSOL","ADANIGREEN","AMBUJACEM","DMART","BAJAJHLDNG","BANKBARODA","BPCL","BOSCHLTD","BRITANNIA",
    "CGPOWER","CANBK","DLF","GAIL","GODREJCP","HDFCAMC","HINDZINC","HYUNDAI","IOC","IRFC",
    "JINDALSTEL","LTM","LODHA","MAZDOCK","MUTHOOTFIN","PIDILITIND","PFC","PNB","RECLTD","SHREECEM",
    "ENRIN","SIEMENS","SOLARINDS","TATACAP","TATAPOWER","UNIONBANK","UNITDSPR","VBL","VEDL","ZYDUSLIFE"
];
