// AI SMART SCANNER — GOOGLE APPS SCRIPT API V6
// Canonical webhook source. Performance optimized for the very wide SCANNER sheet.

var ALLOWED_SHEETS={SCANNER:true,Dashboard:true,ACCURACY:true,PARAMETER_MASTER:true,"Parameter List":true,EQUITY:true,CALL_OPTIONS:true,PUT_OPTIONS:true,SCANNER_STATUS:true};
var WIDE_SHEETS={SCANNER:true,ACCURACY:true};

function doPost(e){var lock=LockService.getScriptLock();try{lock.waitLock(30000);if(!e||!e.postData||!e.postData.contents)return jsonResponse({success:false,error:"No POST data received"});var p=JSON.parse(String(e.postData.contents||""));if(!p||typeof p!=="object")return jsonResponse({success:false,error:"Invalid payload"});var a=String(p.action||"").trim();if(a==="scanner_status"){var s=p.scannerStatus||p.status||{};var sr=updateScannerStatus(s);return jsonResponse({success:true,action:a,sheet:"SCANNER_STATUS",status:s.status||"UNKNOWN",rowCount:sr.rowCount,timestamp:new Date().toISOString()});}if(a==="updateAccuracy"){var ur=updateAccuracyRows(p.updates||p.rows||[]);return jsonResponse({success:true,action:a,sheet:"ACCURACY",updated:ur.updated,notFound:ur.notFound,timestamp:new Date().toISOString()});}if(a!=="replaceSheet"&&a!=="appendRows")return jsonResponse({success:false,error:"Unknown action: "+a});var name=String(p.sheet||"").trim();if(!name)return jsonResponse({success:false,error:"Missing sheet name"});if(!ALLOWED_SHEETS[name])return jsonResponse({success:false,error:"Sheet not allowed: "+name});var headers=normalizeHeaders(p.headers||[]),rows=Array.isArray(p.rows)?p.rows:[];if(!headers.length)return jsonResponse({success:false,error:"No headers supplied for sheet: "+name});for(var h=0;h<headers.length;h++)if(!headers[h])return jsonResponse({success:false,error:"Headers cannot contain empty column names"});var r=a==="replaceSheet"?replaceSheet(name,headers,rows):appendRows(name,headers,rows);return jsonResponse({success:true,action:a,sheet:name,rowCount:r.rowCount,columnCount:r.columnCount,timestamp:new Date().toISOString()});}catch(err){console.error(err&&err.stack?err.stack:err);return jsonResponse({success:false,error:err&&err.message?err.message:String(err),timestamp:new Date().toISOString()});}finally{try{lock.releaseLock();}catch(_){} }}

function getSpreadsheet(){var s=SpreadsheetApp.getActiveSpreadsheet();if(!s)throw new Error("Unable to access active spreadsheet");return s;}
function getOrCreateSheet(s,n){return s.getSheetByName(n)||s.insertSheet(n);}

function replaceSheet(name,headers,rows){var s=getOrCreateSheet(getSpreadsheet(),name);s.clear();var out=[headers];for(var i=0;i<rows.length;i++)out.push(normalizeRow(rows[i],headers.length));s.getRange(1,1,out.length,headers.length).setValues(out);lightFormat(s,out.length,headers.length,name);SpreadsheetApp.flush();return{rowCount:rows.length,columnCount:headers.length};}

function appendRows(name,headers,rows){var s=getOrCreateSheet(getSpreadsheet(),name);if(s.getLastRow()===0){s.getRange(1,1,1,headers.length).setValues([headers]);lightFormat(s,1,headers.length,name);}else{var n=s.getLastColumn();if(n!==headers.length)throw new Error("Header column mismatch for sheet '"+name+"'. Existing: "+n+", Incoming: "+headers.length);var eh=s.getRange(1,1,1,n).getValues()[0];for(var h=0;h<headers.length;h++)if(String(eh[h]).trim()!==String(headers[h]).trim())throw new Error("Header mismatch at column "+(h+1)+" in sheet '"+name+"'");}if(!rows.length)return{rowCount:0,columnCount:headers.length};var out=[];for(var i=0;i<rows.length;i++)out.push(normalizeRow(rows[i],headers.length));s.getRange(s.getLastRow()+1,1,out.length,headers.length).setValues(out);SpreadsheetApp.flush();return{rowCount:out.length,columnCount:headers.length};}

// Critical fix: no autoResizeColumns and no filter work on SCANNER/ACCURACY.
// Those operations were causing the webhook to hit the 30s lock/HTTP timeout.
function lightFormat(s,rowCount,colCount,name){if(!colCount)return;s.getRange(1,1,1,colCount).setFontWeight("bold").setWrap(false);s.setFrozenRows(1);if(!WIDE_SHEETS[name]&&rowCount>1){try{var f=s.getFilter();if(f)f.remove();s.getRange(1,1,rowCount,colCount).createFilter();}catch(e){console.log("Filter skipped: "+e.message);}}}

function updateScannerStatus(st){var s=getOrCreateSheet(getSpreadsheet(),"SCANNER_STATUS");var h=["Last Scan Time","Last Scan Time IST","Status","Source","Broker","Universe","Stocks Scanned","Successful Scans","Failed Scans","CALL Candidates","PUT Candidates","TRADE","WATCH","REJECT","Duration Seconds","Duration MS"];var v=[st.lastScanTime||"",st.lastScanTimeIST||"",st.status||"",st.lastScanSource||"",st.broker||"",st.universe||"",num(st.stocksScanned),num(st.successfulScans),num(st.failedScans),num(st.callCandidates),num(st.putCandidates),num(st.tradeCount),num(st.watchCount),num(st.rejectCount),num(st.elapsedSeconds),num(st.durationMs)];s.clear();s.getRange(1,1,2,h.length).setValues([h,v]);lightFormat(s,2,h.length,"SCANNER_STATUS");SpreadsheetApp.flush();return{rowCount:1,columnCount:h.length};}

function updateAccuracyRows(updates){if(!Array.isArray(updates))throw new Error("updates must be an array");if(!updates.length)return{updated:0,notFound:0};var s=getOrCreateSheet(getSpreadsheet(),"ACCURACY"),lr=s.getLastRow(),lc=s.getLastColumn();if(lr<2||lc<1)return{updated:0,notFound:updates.length};var h=s.getRange(1,1,1,lc).getValues()[0],idc=findCol(h,"predictionId");if(idc<0)throw new Error("ACCURACY sheet does not contain predictionId column");var d=s.getRange(2,1,lr-1,lc).getValues(),map={};for(var i=0;i<d.length;i++){var id=String(d[i][idc]||"").trim();if(id)map[id]=i;}var u=0,nf=0,fields=["actualHigh","actualLow","maxFavorableMove","maxAdverseMove","maxFavorablePercent","maxAdversePercent","target1Reached","target2Reached","stopLossReached","target1Time","target2Time","stopLossTime","finalOutcome","completedTime"];for(var x=0;x<updates.length;x++){var z=updates[x];if(!z||!z.predictionId){nf++;continue;}var pid=String(z.predictionId).trim();if(map[pid]===undefined){nf++;continue;}for(var j=0;j<fields.length;j++){var f=fields[j],c=findCol(h,f);if(c>=0&&z[f]!==undefined)d[map[pid]][c]=cell(z[f]);}u++;}s.getRange(2,1,d.length,lc).setValues(d);SpreadsheetApp.flush();return{updated:u,notFound:nf};}

function findCol(h,n){n=String(n).trim().toLowerCase();for(var i=0;i<h.length;i++)if(String(h[i]).trim().toLowerCase()===n)return i;return-1;}
function normalizeHeaders(h){if(!Array.isArray(h))return[];return h.map(function(v){return v===null||v===undefined?"":String(v).trim();});}
function normalizeRow(r,n){if(!Array.isArray(r))r=[];var o=[];for(var i=0;i<n;i++)o.push(i<r.length?cell(r[i]):"");return o;}
function cell(v){if(v===null||v===undefined)return"";if(Object.prototype.toString.call(v)==="[object Date]")return isNaN(v.getTime())?"":v;if(typeof v==="number")return isFinite(v)?v:"";if(typeof v==="boolean")return v;if(typeof v==="object"){try{return JSON.stringify(v);}catch(e){return String(v);}}return String(v);}
function num(v){var n=Number(v);return isFinite(n)?n:0;}
function jsonResponse(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}
function doGet(){return jsonResponse({success:true,service:"AI Smart Scanner Google Sheet API",status:"RUNNING",version:"V6",performanceMode:true,supportedActions:["replaceSheet","appendRows","updateAccuracy","scanner_status"],supportedSheets:Object.keys(ALLOWED_SHEETS),timestamp:new Date().toISOString()});}
