// ============================================================
// AI SMART SCANNER — ACCURACY TRACKER
// ============================================================
// Accuracy measures how far price moved toward the predicted target.
// Example: Entry 420, Target 425, High 424 => 80% accuracy.
// ============================================================

const ACCURACY_HEADERS=["recordId","date","time","timestamp","stock","symbol","direction","decision","confidence","stockPriceAtSignal","stockEntry","stockStopLoss","stockTarget1","stockTarget2","highestStockPriceReached","highestStockPriceDate","highestStockPriceTime","lowestStockPriceReached","lowestStockPriceDate","lowestStockPriceTime","maxFavorableMove","maxFavorableMovePercent","maxAdverseMove","maxAdverseMovePercent","stopLossReached","stopLossReachedDate","stopLossReachedTime","target1Reached","target1ReachedDate","target1ReachedTime","target2Reached","target2ReachedDate","target2ReachedTime","targetSLReached","slReason","resultTime","resultPrice","accuracyPercent","evaluationStatus","evaluationDate"];
const number=v=>{const n=Number(v);return Number.isFinite(n)?n:null;};
function directionOf(p){const d=String(p?.direction||p?.stockDirection||p?.technicalDirection||"").trim().toUpperCase();if(["CALL","BUY","BULLISH","LONG","UP"].includes(d))return"CALL";if(["PUT","SELL","BEARISH","SHORT","DOWN"].includes(d))return"PUT";return"NO DIRECTION";}
function parseDate(v){if(!v)return null;const d=v instanceof Date?new Date(v.getTime()):new Date(v);return Number.isNaN(d.getTime())?null:d;}
function makeRecordId(p,t=new Date()){return `${String(p?.symbol||p?.stock||"UNKNOWN").trim().toUpperCase()}_${t.getTime()}`;}
function createAccuracyRecord(p,t=new Date()){const price=number(p?.price??p?.stockPrice),entry=number(p?.entry??p?.stockEntry??price);return{recordId:makeRecordId(p,t),date:t.toISOString().slice(0,10),time:t.toISOString().slice(11,19),timestamp:t.toISOString(),stock:p?.stock||p?.symbol||"",symbol:p?.symbol||p?.stock||"",direction:directionOf(p),decision:p?.optionsDecision||p?.decision||p?.signal||"",confidence:number(p?.confidence??p?.optionsConfidence),stockPriceAtSignal:price,stockEntry:entry,stockStopLoss:number(p?.stopLoss??p?.stockStopLoss),stockTarget1:number(p?.target1??p?.stockTarget1),stockTarget2:number(p?.target2??p?.stockTarget2),highestStockPriceReached:price,highestStockPriceDate:t.toISOString().slice(0,10),highestStockPriceTime:t.toISOString().slice(11,19),lowestStockPriceReached:price,lowestStockPriceDate:t.toISOString().slice(0,10),lowestStockPriceTime:t.toISOString().slice(11,19),maxFavorableMove:0,maxFavorableMovePercent:0,maxAdverseMove:0,maxAdverseMovePercent:0,stopLossReached:false,stopLossReachedDate:"",stopLossReachedTime:"",target1Reached:false,target1ReachedDate:"",target1ReachedTime:"",target2Reached:false,target2ReachedDate:"",target2ReachedTime:"",targetSLReached:"PENDING",slReason:"",resultTime:"",resultPrice:null,accuracyPercent:0,evaluationStatus:"PENDING",evaluationDate:""};}
function reachedLevel(direction,high,low,level,type){if(!Number.isFinite(level)||level<=0)return false;if(direction==="CALL")return type==="TARGET"?high>=level:low<=level;if(direction==="PUT")return type==="TARGET"?low<=level:high>=level;return false;}
function touchInCandle(direction,candle,level,type){const h=number(candle?.high),l=number(candle?.low);return Number.isFinite(h)&&Number.isFinite(l)&&reachedLevel(direction,h,l,level,type);}
function firstTouchEvent(candles,direction,level,type){if(!Number.isFinite(level)||level<=0)return null;for(const c of candles){if(!touchInCandle(direction,c,level,type))continue;const time=parseDate(c?.time);if(time)return{time,price:level};}return null;}
function calculateProgressAccuracy(direction,entry,target,high,low){if(![entry,target].every(Number.isFinite)||entry<=0||target<=0||target===entry)return 0;let progress=direction==="CALL"?(high-entry)/(target-entry):(entry-low)/(entry-target);if(!Number.isFinite(progress))return 0;return Number(Math.min(100,Math.max(0,progress*100)).toFixed(2));}
function stopLossReason(direction,record,candle){const sl=number(record?.stockStopLoss),h=number(candle?.high),l=number(candle?.low);if(!Number.isFinite(sl))return"STOP_LOSS_LEVEL_INVALID";if(direction==="CALL"&&Number.isFinite(l)&&l<=sl)return"CALL_PRICE_BREACHED_STOP_LOSS";if(direction==="PUT"&&Number.isFinite(h)&&h>=sl)return"PUT_PRICE_BREACHED_STOP_LOSS";return"STOP_LOSS_HIT";}
function evaluateAccuracy(record,candles,evaluatedAt=new Date()){if(!record||!Array.isArray(candles)||!candles.length)return record;const direction=String(record.direction||"").toUpperCase(),now=parseDate(evaluatedAt)||new Date();if(!["CALL","PUT"].includes(direction)){record.evaluationStatus="NO_DIRECTION";return record;}const entry=number(record.stockEntry);if(!Number.isFinite(entry)||entry<=0){record.evaluationStatus="INVALID_ENTRY";return record;}const signalTime=parseDate(record.timestamp||`${record.date||""}T${record.time||""}`);const cs=candles.filter(c=>{const t=parseDate(c?.time);return t&&t<=now&&(!signalTime||t>=signalTime)}).sort((a,b)=>(parseDate(a?.time)?.getTime()||0)-(parseDate(b?.time)?.getTime()||0));if(!cs.length){record.evaluationStatus="WAITING_FOR_POST_SIGNAL_DATA";return record;}let high=-Infinity,low=Infinity,highTime=null,lowTime=null;for(const c of cs){const h=number(c?.high),l=number(c?.low),t=parseDate(c?.time);if(Number.isFinite(h)&&h>high){high=h;highTime=t;}if(Number.isFinite(l)&&l<low){low=l;lowTime=t;}}if(!Number.isFinite(high)||!Number.isFinite(low))return record;record.highestStockPriceReached=high;record.lowestStockPriceReached=low;record.highestStockPriceDate=highTime?.toISOString().slice(0,10)||"";record.highestStockPriceTime=highTime?.toISOString().slice(11,19)||"";record.lowestStockPriceDate=lowTime?.toISOString().slice(0,10)||"";record.lowestStockPriceTime=lowTime?.toISOString().slice(11,19)||"";const favorable=direction==="CALL"?high-entry:entry-low,adverse=direction==="CALL"?entry-low:high-entry;record.maxFavorableMove=Number(Math.max(0,favorable).toFixed(2));record.maxFavorableMovePercent=Number((Math.max(0,favorable)/entry*100).toFixed(2));record.maxAdverseMove=Number(Math.max(0,adverse).toFixed(2));record.maxAdverseMovePercent=Number((Math.max(0,adverse)/entry*100).toFixed(2));record.accuracyPercent=calculateProgressAccuracy(direction,entry,number(record.stockTarget1),high,low);const stopEvent=firstTouchEvent(cs,direction,number(record.stockStopLoss),"STOP"),targetEvent=firstTouchEvent(cs,direction,number(record.stockTarget1),"TARGET");if(stopEvent){record.stopLossReached=true;record.stopLossReachedDate=stopEvent.time.toISOString().slice(0,10);record.stopLossReachedTime=stopEvent.time.toISOString().slice(11,19);const stopCandle=cs.find(c=>{const t=parseDate(c?.time);return t&&t.getTime()===stopEvent.time.getTime()});record.slReason=stopLossReason(direction,record,stopCandle);}
if(targetEvent){record.target1Reached=true;record.target1ReachedDate=targetEvent.time.toISOString().slice(0,10);record.target1ReachedTime=targetEvent.time.toISOString().slice(11,19);}
const events=[stopEvent?{type:"SL",...stopEvent}:null,targetEvent?{type:"TARGET",...targetEvent}:null].filter(Boolean).sort((a,b)=>a.time-a.time);if(events.length&&(!events[1]||events[0].time.getTime()!==events[1].time.getTime())){const first=events[0];record.targetSLReached=first.type;record.resultTime=first.time.toISOString();record.resultPrice=first.price;record.accuracyPercent=first.type==="TARGET"?100:calculateProgressAccuracy(direction,entry,number(record.stockTarget1),high,low);record.evaluationStatus=first.type==="TARGET"?"TARGET_REACHED":"SL_REACHED";}else if(events.length===1){const first=events[0];record.targetSLReached=first.type;record.resultTime=first.time.toISOString();record.resultPrice=first.price;record.accuracyPercent=first.type==="TARGET"?100:calculateProgressAccuracy(direction,entry,number(record.stockTarget1),high,low);record.evaluationStatus=first.type==="TARGET"?"TARGET_REACHED":"SL_REACHED";}else{record.targetSLReached="PENDING";record.resultTime="";record.resultPrice=null;record.evaluationStatus="IN_PROGRESS";}record.evaluationDate=now.toISOString();return record;}
function accuracyRecordToRow(record){return ACCURACY_HEADERS.map(h=>record?.[h]??"");}
module.exports={ACCURACY_HEADERS,createAccuracyRecord,evaluateAccuracy,accuracyRecordToRow,directionOf};