require("dotenv").config();
const {setBroker,getActiveBroker,loadInstruments}=require("./brokers");
const {loadSymbolMaster}=require("./services/symbolService");
const {scanStocks}=require("./scanner");
const {calculateOptionsDecisions}=require("./optionsDecisionEngine");
const {updateGoogleSheet,buildScannerStatus}=require("./googleSheet");
const {updateStrategySheets}=require("./strategySheets");
const {buildDashboard}=require("./dashboard");
const {createAccuracyRecord,evaluateAccuracy}=require("./accuracyTracker");
const {evaluateLiveAccuracy}=require("./liveAccuracyEvaluator");
const {getWholeNseUniverse}=require("./marketUniverse");
const {getTop500ByLiveVolume,filterOptionEligibleStocks}=require("./liveMarket");
const {getUnderlyingOIMood}=require("./underlyingOI");
const {DIVIDEND_LONG_TERM_SYMBOLS}=require("./dividendUniverse");
const ONE_TRADE_LIMIT=1,STOCK_BATCH_SIZE=25,TOP_EQUITY_LIVE_STOCKS=50,TOP_SCANNER_STOCKS=20,TOP_OPTION_ELIGIBLE_STOCKS=100,DASHBOARD_MIN_SCORE=5,DASHBOARD_FALLBACK_ROWS=5;
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const key=r=>String(r?.stock??r?.symbol??r?.name??"").trim().toUpperCase();
const decision=r=>String(r?.optionsDecision??r?.decision??"").trim().toUpperCase();
const score=r=>Math.abs(num(r?.scannerScore??r?.score));
const confidence=r=>num(r?.optionsConfidence??r?.confidence);
const hasOptionContract=r=>Boolean(r?.optionInstrumentKey||r?.optionSymbol||r?.recommendedStrike||r?.optionType);
const optionLtpValid=r=>num(r?.optionPremiumEntry)>0;
async function scanInBatches(symbols){const all=[];for(let i=0;i<symbols.length;i+=STOCK_BATCH_SIZE){const batch=symbols.slice(i,i+STOCK_BATCH_SIZE);console.log(`STOCK BATCH ${i+1}-${Math.min(i+STOCK_BATCH_SIZE,symbols.length)}`);try{const result=await scanStocks(batch);const rows=Array.isArray(result?.allResults)?result.allResults:(Array.isArray(result)?result:[]);all.push(...rows);}catch(e){console.error(`Batch failed: ${e?.message||e}`);for(const s of batch)all.push({stock:s,symbol:s,qualified:false,rejectionReason:"BATCH_ERROR"});}}const map=new Map();for(const r of all)map.set(key(r),r);const unique=[...map.values()];return{allResults:unique,qualified:unique.filter(r=>r?.qualified===true),rejected:unique.filter(r=>r?.qualified===false)};}
async function enrichUnderlyingOI(rows=[]){return Promise.all((Array.isArray(rows)?rows:[]).map(async r=>{try{const oi=await getUnderlyingOIMood({instrumentKey:r.instrumentKey,currentPrice:num(r.currentPrice??r.price),previousPrice:num(r.previousPrice??r.prevPrice??r.previousClose)});return{...r,oiCheckAttempted:true,oiMood:oi.mood||"UNKNOWN",oiSentiment:oi.sentiment||"UNKNOWN",oiDataAvailable:oi.dataAvailable===true,oiPriceChangePercent:num(oi.priceChangePercent),oiChangePercent:num(oi.oiChangePercent),oi:num(oi.oi),previousOI:num(oi.previousOI),underlyingOISource:oi.source||"",underlyingOIReason:oi.reason||""};}catch(e){return{...r,oiCheckAttempted:true,oiMood:"UNKNOWN",oiSentiment:"UNKNOWN",oiDataAvailable:false,oiPriceChangePercent:0,oiChangePercent:0,underlyingOIReason:`ENRICHMENT_FAILED:${e?.message||e}`};}}));}
function merge(stocks,decisions){const m=new Map((Array.isArray(decisions)?decisions:[]).map(r=>[key(r),r]));return stocks.map(s=>m.has(key(s))?{...s,...m.get(key(s))}:s);}
function chooseOne(decisions){return(Array.isArray(decisions)?decisions:[]).filter(r=>decision(r)==="TRADE").sort((a,b)=>(confidence(b)-confidence(a))||(score(b)-score(a))||(num(b.riskReward)-num(a.riskReward))).slice(0,ONE_TRADE_LIMIT);}
function rankOptionReady(rows){return[...(Array.isArray(rows)?rows:[])].filter(r=>r?.qualified===true&&['TRADE','WATCH'].includes(decision(r))&&hasOptionContract(r)&&optionLtpValid(r)).sort((a,b)=>(score(b)-score(a))||(confidence(b)-confidence(a))).slice(0,TOP_SCANNER_STOCKS);}
function selectDashboardCandidates(rows){const directions=["BULLISH","BEARISH","LONG","SHORT","BUY","SELL","CALL","PUT","CE","PE"];const list=[...(Array.isArray(rows)?rows:[])].filter(Boolean).map(r=>{const rating=String(r?.rating??"").toUpperCase();const aiRating=String(r?.aiRating??"").toUpperCase();const signal=String(r?.signal??"").toUpperCase();const reject=String(r?.rejectionReason??"").toUpperCase();if(rating.includes("AVOID")||signal.includes("AVOID")||rating.includes("REJECT")||reject.includes("ERROR"))return null;const explicit=String(r?.direction??r?.finalDirection??r?.stockDirection??r?.technicalDirection??"").trim().toUpperCase();let d=explicit;if(!directions.includes(d)){const call=num(r?.callScore),put=num(r?.putScore);if(call>put)d="BULLISH";else if(put>call)d="BEARISH";}return d&&directions.includes(d)?{...r,dashboardDirection:d}:null;}).filter(Boolean);const ranked=list.sort((a,b)=>(score(b)-score(a))||(confidence(b)-confidence(a)));const actionable=ranked.filter(r=>r?.qualified===true&&score(r)>=DASHBOARD_MIN_SCORE&&String(r?.rejectionReason??"").toUpperCase().indexOf("ERROR")<0);return actionable.slice(0,DASHBOARD_FALLBACK_ROWS);}
async function evaluateDashboardAccuracy(rows=[],broker){const evaluated=[];for(const row of Array.isArray(rows)?rows:[]){const record=createAccuracyRecord(row,new Date());try{const symbol=row?.instrumentKey||row?.symbol||row?.stock;if(!symbol)throw new Error("Missing instrument/symbol");const candles=await broker.getHistoricalData(symbol,"FIVE_MINUTE");evaluateAccuracy(record,candles,new Date());}catch(e){record.evaluationStatus=`LIVE_DATA_FAILED:${e?.message||e}`;record.targetSLReached="PENDING";record.evaluationDate=new Date().toISOString();console.error(`Accuracy live-data failed for ${key(row)}: ${e?.message||e}`);}evaluated.push({...row,...record});}return evaluated;}
async function main(){const started=new Date();console.log("\n=== AI SMART SCANNER V13 ===");const brokerName=String(process.env.BROKER||"UPSTOX").trim().toUpperCase();setBroker(brokerName);const broker=getActiveBroker();await broker.login();try{await loadInstruments()}catch(e){console.log(`Instrument load warning: ${e?.message||e}`)}try{await loadSymbolMaster()}catch(e){console.log(`Symbol master warning: ${e?.message||e}`)}const universe=await getWholeNseUniverse(broker);console.log(`Universe source: ${universe.name} | WHOLE_NSE=${universe.symbols.length} | optionEligible=${universe.optionEligibleCount}`);const top500Ranking=await getTop500ByLiveVolume(universe.symbols,broker,500),top500=Array.isArray(top500Ranking?.top)?top500Ranking.top:[];if(!top500.length)throw new Error("Live Top 500 ranking returned no stocks");
const equityTop50Rows=(top500Ranking?.top||[]).slice(0,TOP_EQUITY_LIVE_STOCKS);const equityTop50Symbols=equityTop50Rows.map(x=>x.symbol).filter(Boolean);if(!equityTop50Symbols.length)throw new Error("Live Equity Top-50 ranking returned no stocks");console.log(`EQUITY PIPELINE: live Top-50=${equityTop50Symbols.length} → technical/AI scan → Top-20`);const dividendUniverseSymbols=DIVIDEND_LONG_TERM_SYMBOLS.filter(s=>!equityTop50Symbols.includes(s));console.log(`DIVIDEND EQUITY PIPELINE: mandatory=${DIVIDEND_LONG_TERM_SYMBOLS.length} | additional scan=${dividendUniverseSymbols.length}`);const equityScan=await scanInBatches(equityTop50Symbols),equityTop50ScanData=equityScan.allResults;const equityScannerData=[...equityTop50ScanData].sort((a,b)=>(score(b)-score(a))||(confidence(b)-confidence(a))).slice(0,TOP_SCANNER_STOCKS);console.log(`EQUITY PIPELINE: scanned Top-50=${equityTop50ScanData.length} → selected Top-20=${equityScannerData.length}`);const dividendScan=await scanInBatches(dividendUniverseSymbols),dividendScannerData=[...equityScannerData,...dividendScan.allResults];
const optionPreflight=await filterOptionEligibleStocks(top500,broker,TOP_OPTION_ELIGIBLE_STOCKS);if(!optionPreflight.length)throw new Error(`No live-tradable option candidates found in live Top 500 (top500=${top500.length}, optionLiquidityPool=dynamic)`);const top100OptionRows=optionPreflight.slice(0,TOP_OPTION_ELIGIBLE_STOCKS),top20=top100OptionRows.slice(0,TOP_SCANNER_STOCKS),optionScanUniverse=top20.map(x=>x.symbol).filter(Boolean);console.log(`OPTION PIPELINE: WHOLE_NSE=${universe.symbols.length} | Top-500=${top500.length} | dynamic option-eligible=${top100OptionRows.length} | Top-20 scan=${optionScanUniverse.length}`);const optionUniverseScan=await scanInBatches(optionScanUniverse),optionUniverseRows=optionUniverseScan.allResults;const optionLiveMetaBySymbol=new Map(optionPreflight.map(x=>[String(x.symbol).toUpperCase(),x]));const optionRowsWithLiveMeta=optionUniverseRows.map(r=>{const pre=optionPreflight.find(x=>key(x)===key(r));const live=optionLiveMetaBySymbol.get(key(r))||{};return pre?{...r,...live,...pre,optionEligible:r.qualified===true&&r.volumeConfirmed5===true}:r;});const enriched=await enrichUnderlyingOI(optionRowsWithLiveMeta);let decisions=[];try{decisions=await calculateOptionsDecisions(enriched)}catch(e){console.error(`Options engine failed: ${e?.message||e}`)}const merged=merge(enriched,decisions).map(r=>({...r,optionEligible:r.qualified===true&&['TRADE','WATCH'].includes(decision(r))&&hasOptionContract(r)&&optionLtpValid(r)}));const optionReady=rankOptionReady(merged);const dashboardUniverse=[...equityScannerData,...merged];const dashboardRows=selectDashboardCandidates(dashboardUniverse);const finalTrade=chooseOne(optionReady);console.log(`OPTION INTERNAL SCAN: ${enriched.length} preflight-valid Top-20 rows`);console.log(`OPTION OI: attempted=${enriched.filter(r=>r?.oiCheckAttempted===true).length} available=${enriched.filter(r=>r?.oiDataAvailable===true).length} unknown=${enriched.filter(r=>r?.oiCheckAttempted===true&&r?.oiDataAvailable!==true).length}`);console.log(`DASHBOARD SELECTION: ${dashboardRows.length} actionable rows | qualified=${dashboardRows.filter(r=>r?.qualified===true).length} | top score=${dashboardRows[0]?score(dashboardRows[0]):0}`);
const scannerData=merged.map(r=>{const setupEntry=num(r.stockEntry??r.entry);const finalOptionEligible=r.qualified===true&&r.volumeConfirmed5===true&&['TRADE','WATCH'].includes(decision(r))&&hasOptionContract(r)&&optionLtpValid(r);return{...r,optionEligible:finalOptionEligible,entry:setupEntry,stockEntry:setupEntry,underlyingEntry:setupEntry,marketEntry:setupEntry,triggerPrice:setupEntry,stockStopLoss:num(r.stockStopLoss??r.stopLoss),stockTarget1:num(r.stockTarget1??r.target1),stockTarget2:num(r.stockTarget2??r.target2)}});const combinedScannerData=[...equityScannerData,...scannerData].sort((a,b)=>(score(b)-score(a))||(confidence(b)-confidence(a))).slice(0,TOP_SCANNER_STOCKS);
const accuracyInput=dashboardRows.map(r=>{const full=dashboardUniverse.find(s=>key(s)===key(r));return full?{...full,...r}:r});const accuracyData=await evaluateDashboardAccuracy(accuracyInput,broker);let core=false,strategy=false;try{await updateGoogleSheet({scannerData:combinedScannerData,dashboardData:dashboardRows,accuracyData});core=true}catch(e){console.error(`Sheet update failed: ${e?.message||e}`)}try{const liveAccuracy=await evaluateLiveAccuracy(broker);console.log(`📡 LIVE ACCURACY REFRESH: found=${liveAccuracy.found} evaluated=${liveAccuracy.evaluated} updated=${liveAccuracy.updated} skipped=${liveAccuracy.skipped}`)}catch(e){console.error(`Live Accuracy refresh failed: ${e?.message||e}`)}try{await updateStrategySheets(combinedScannerData,decisions,equityScannerData,DIVIDEND_LONG_TERM_SYMBOLS.map(s=>dividendScannerData.find(r=>key(r)===s)||{stock:s,symbol:s,rejectionReason:"NOT_SCANNED"}));strategy=true}catch(e){console.error(`Strategy sheet update failed: ${e?.message||e}`)}try{await buildDashboard(dashboardUniverse,decisions,universe.symbols.length)}catch(e){console.error(`Dashboard update failed: ${e?.message||e}`)}const counts={call:dashboardRows.filter(r=>["CALL","CE"].includes(String(r.optionType).toUpperCase())).length,put:dashboardRows.filter(r=>["PUT","PE"].includes(String(r.optionType).toUpperCase())).length,trade:decisions.filter(r=>decision(r)==="TRADE").length,watch:decisions.filter(r=>decision(r)==="WATCH").length,reject:decisions.filter(r=>decision(r)==="REJECT").length};const elapsed=((Date.now()-started.getTime())/1000).toFixed(1),status=buildScannerStatus({status:core&&strategy?"SUCCESS":"PARTIAL_FAILURE",startedAt:started,universe:universe.name,broker:brokerName,scanned:combinedScannerData.length,successfulScans:combinedScannerData.filter(r=>!String(r.rejectionReason||"").includes("ERROR")).length,failedScans:combinedScannerData.filter(r=>String(r.rejectionReason||"").includes("ERROR")).length,callCandidates:counts.call,putCandidates:counts.put,tradeCount:counts.trade,watchCount:counts.watch,rejectCount:counts.reject,elapsedSeconds:elapsed});try{await updateGoogleSheet({action:"scanner_status",scannerStatus:status})}catch(e){console.error(`Status update failed: ${e?.message||e}`)}return{universe,top500,equityTop50:equityTop50Symbols,equityTop20:equityScannerData,optionBuyingUniverse:optionPreflight.map(x=>x.symbol),optionUniverseSymbols:top100OptionRows.map(x=>x.symbol),optionLiveRows:top100OptionRows,optionPreflight:top100OptionRows,top100OptionRows,top20,optionUniverseRows,optionReadyTop20:optionReady,scannerData:combinedScannerData,completeScannerData:equityScannerData,dividendScannerData,optionScannerData:enriched,optionDecisions:decisions,finalDashboard:dashboardRows,finalTrade,scannerStatus:status};}
if(require.main===module)main().catch(e=>{console.error(`FATAL: ${e?.stack||e}`);process.exitCode=1});
module.exports={main,scanInBatches,chooseOne,rankOptionReady,selectDashboardCandidates};
