// CHART PATTERN ENGINE
function num(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}
function candlesOf(c){return Array.isArray(c)?c.map(x=>({open:num(x?.open,NaN),high:num(x?.high,NaN),low:num(x?.low,NaN),close:num(x?.close,NaN),volume:num(x?.volume,0)})).filter(x=>[x.open,x.high,x.low,x.close].every(Number.isFinite)&&x.high>=x.low&&x.open>0&&x.close>0):[];}
function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0;}
function range(a){return{high:a.length?Math.max(...a.map(x=>x.high)):0,low:a.length?Math.min(...a.map(x=>x.low)):0};}
function slope(a){if(a.length<2)return 0;const n=a.length,x=(n-1)/2,y=avg(a);let p=0,q=0;a.forEach((v,i)=>{p+=(i-x)*(v-y);q+=(i-x)**2;});return q?p/q:0;}
function near(a,b,t=.025){return a>0&&b>0&&Math.abs(a-b)/Math.max(a,b)<=t;}
function swings(c,l=2){const h=[],lo=[];for(let i=l;i<c.length-l;i++){let hi=true,low=true;for(let j=1;j<=l;j++){if(c[i].high<=c[i-j].high||c[i].high<=c[i+j].high)hi=false;if(c[i].low>=c[i-j].low||c[i].low>=c[i+j].low)low=false;}if(hi)h.push(c[i].high);if(low)lo.push(c[i].low);}return{h,lo};}
function out(name,dir,status,conf,score,extra={}){return{chartPattern:name,patternStatus:status,patternDirection:dir,patternTimeframe:'1D',patternConfidence:Math.round(Math.max(0,Math.min(100,conf))),patternScore:Math.round(Math.max(0,Math.min(10,score))),patternContribution:0,patternBreakoutLevel:num(extra.breakoutLevel),patternInvalidationLevel:num(extra.invalidationLevel),patternTarget:num(extra.target),patternDescription:extra.description||'',patternDetectedAt:new Date().toISOString()};}
function detectChartPattern(input){const c=candlesOf(input);if(c.length<20)return out('NONE','NEUTRAL','NONE',0,0,{description:'Insufficient candles for reliable pattern detection.'});const last=c[c.length-1],prev=c[c.length-2],body=Math.abs(last.close-last.open),prevBody=Math.abs(prev.close-prev.open);if(last.close>last.open&&prev.close<prev.open&&last.open<=prev.close&&last.close>=prev.open&&body>prevBody*1.05)return out('Bullish Engulfing','BULLISH','FORMED',78,5,{breakoutLevel:last.high,invalidationLevel:prev.low,target:last.high+(last.high-prev.low)*.5,description:'Latest bullish candle engulfs the prior bearish candle.'});if(last.close<last.open&&prev.close>prev.open&&last.open>=prev.close&&last.close<=prev.open&&body>prevBody*1.05)return out('Bearish Engulfing','BEARISH','FORMED',78,5,{breakoutLevel:last.low,invalidationLevel:prev.high,target:last.low-(prev.high-last.low)*.5,description:'Latest bearish candle engulfs the prior bullish candle.'});const recent=c.slice(-20),earlier=c.slice(-40,-20),all=c.slice(-60),sw=swings(all),rh=sw.h.slice(-3),rl=sw.lo.slice(-3),rr=range(recent),er=range(earlier),avgVol=avg(recent.map(x=>x.volume).filter(v=>v>0)),volBreak=avgVol>0&&last.volume>=avgVol*1.2;if(earlier.length>=10){const recentPct=rr.low?(rr.high-rr.low)/rr.low:99,priorPct=er.low?(er.high-er.low)/er.low:99,up=earlier[earlier.length-1].close>earlier[0].close*1.05,down=earlier[earlier.length-1].close<earlier[0].close*.95;if(up&&recentPct<priorPct*.65)return out('Bull Flag','BULLISH',last.close>=rr.high&&volBreak?'BREAKOUT':'BUILDING',last.close>=rr.high&&volBreak?90:76,last.close>=rr.high&&volBreak?9:4,{breakoutLevel:rr.high,invalidationLevel:rr.low,target:rr.high+(rr.high-rr.low),description:'Strong prior advance followed by a contracting consolidation.'});if(down&&recentPct<priorPct*.65)return out('Bear Flag','BEARISH',last.close<=rr.low&&volBreak?'BREAKOUT':'BUILDING',last.close<=rr.low&&volBreak?90:76,last.close<=rr.low&&volBreak?9:4,{breakoutLevel:rr.low,invalidationLevel:rr.high,target:rr.low-(rr.high-rr.low),description:'Strong prior decline followed by a contracting consolidation.'});}
if(rh.length>=2&&rl.length>=2){const h1=rh[rh.length-2],h2=rh[rh.length-1],l1=rl[rl.length-2],l2=rl[rl.length-1];if(near(h1,h2)&&l2>l1*1.01){const level=(h1+h2)/2,ok=last.close>level;return out('Ascending Triangle','BULLISH',ok?'CONFIRMED':'BUILDING',ok?91:79,ok?9:5,{breakoutLevel:level,invalidationLevel:l1,target:level+(level-l1),description:'Flat resistance with rising swing lows.'});}if(near(l1,l2)&&h2<h1*.99){const level=(l1+l2)/2,ok=last.close<level;return out('Descending Triangle','BEARISH',ok?'CONFIRMED':'BUILDING',ok?91:79,ok?9:5,{breakoutLevel:level,invalidationLevel:h1,target:level-(h1-level),description:'Flat support with falling swing highs.'});}if(near(rl[0],rl[rl.length-1])&&rh.length>=2){const neckline=Math.max(...rh),ok=last.close>neckline;return out('Double Bottom','BULLISH',ok?'CONFIRMED':'FORMED',ok?92:80,ok?9:5,{breakoutLevel:neckline,invalidationLevel:Math.min(...rl),target:neckline+(neckline-Math.min(...rl)),description:'Two comparable swing lows with a neckline between them.'});}if(near(rh[0],rh[rh.length-1])&&rl.length>=2){const neckline=Math.min(...rl),ok=last.close<neckline;return out('Double Top','BEARISH',ok?'CONFIRMED':'FORMED',ok?92:80,ok?9:5,{breakoutLevel:neckline,invalidationLevel:Math.max(...rh),target:neckline-(Math.max(...rh)-neckline),description:'Two comparable swing highs with a neckline between them.'});}}
if(c.length>=50){const first=c.slice(-50,-25),middle=c.slice(-25,-10),handle=c.slice(-10),r1=range(first),r2=range(middle),rh2=range(handle);if(r1.high>0&&r2.low<r1.high*.95&&r2.high>r1.high*.95&&rh2.high<r2.high*1.02&&last.close>rh2.high)return out('Cup and Handle','BULLISH','BREAKOUT',87,8,{breakoutLevel:rh2.high,invalidationLevel:rh2.low,target:rh2.high+(r1.high-r2.low),description:'Rounded recovery followed by a shallow handle and breakout.'});}
const hs=slope(rh),ls=slope(rl);if(rh.length>=2&&rl.length>=2&&hs<0&&ls>0)return out('Ascending Triangle','BULLISH','BUILDING',73,3,{breakoutLevel:rr.high,invalidationLevel:rr.low,target:rr.high+(rr.high-rr.low),description:'Converging price structure with higher lows.'});if(rh.length>=2&&rl.length>=2&&hs<0&&ls<0&&Math.abs(hs)<Math.abs(ls))return out('Rising Wedge','BEARISH','BUILDING',70,3,{breakoutLevel:rr.low,invalidationLevel:rr.high,target:rr.low-(rr.high-rr.low)*.5,description:'Rising boundaries with support advancing faster than resistance.'});if(rh.length>=2&&rl.length>=2&&hs>0&&ls>0&&hs>ls)return out('Falling Wedge','BULLISH','BUILDING',70,3,{breakoutLevel:rr.high,invalidationLevel:rr.low,target:rr.high+(rr.high-rr.low)*.5,description:'Falling boundaries with resistance declining faster than support.'});const mid=(rr.high+rr.low)/2;return out('Rectangle','BULLISH','BUILDING',65,2,{breakoutLevel:rr.high,invalidationLevel:rr.low,target:rr.high+(rr.high-rr.low),description:'Price is consolidating inside a defined horizontal range.'});}
module.exports={detectChartPattern};
