// CHART PATTERN ENGINE V2
// Broad pattern detection: do not restrict the scanner to a small hard-coded
// shortlist. Multiple structural and candlestick detectors are evaluated and
// the strongest reliable candidate is returned. Unknown/unreliable structures
// remain NONE instead of inventing a pattern.
function num(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f;}
function candlesOf(c){return Array.isArray(c)?c.map(x=>({open:num(x?.open,NaN),high:num(x?.high,NaN),low:num(x?.low,NaN),close:num(x?.close,NaN),volume:num(x?.volume,0)})).filter(x=>[x.open,x.high,x.low,x.close].every(Number.isFinite)&&x.high>=x.low&&x.open>0&&x.close>0):[];}
function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0;}
function range(a){return{high:a.length?Math.max(...a.map(x=>x.high)):0,low:a.length?Math.min(...a.map(x=>x.low)):0};}
function slope(a){if(a.length<2)return 0;const n=a.length,x=(n-1)/2,y=avg(a);let p=0,q=0;a.forEach((v,i)=>{p+=(i-x)*(v-y);q+=(i-x)**2;});return q?p/q:0;}
function near(a,b,t=.025){return a>0&&b>0&&Math.abs(a-b)/Math.max(a,b)<=t;}
function pct(a,b){return b>0?(a-b)/b:0;}
function body(c){return Math.abs(c.close-c.open);}
function candleRange(c){return Math.max(c.high-c.low,1e-9);}
function upperWick(c){return c.high-Math.max(c.open,c.close);}
function lowerWick(c){return Math.min(c.open,c.close)-c.low;}
function swings(c,l=2){const h=[],lo=[];for(let i=l;i<c.length-l;i++){let hi=true,low=true;for(let j=1;j<=l;j++){if(c[i].high<=c[i-j].high||c[i].high<=c[i+j].high)hi=false;if(c[i].low>=c[i-j].low||c[i].low>=c[i+j].low)low=false;}if(hi)h.push(c[i].high);if(low)lo.push(c[i].low);}return{h,lo};}
function out(name,dir,status,conf,score,extra={}){return{chartPattern:name,patternStatus:status,patternDirection:dir,patternTimeframe:'1D',patternConfidence:Math.round(Math.max(0,Math.min(100,conf))),patternScore:Math.round(Math.max(0,Math.min(10,score))),patternContribution:0,patternBreakoutLevel:num(extra.breakoutLevel),patternInvalidationLevel:num(extra.invalidationLevel),patternTarget:num(extra.target),patternDescription:extra.description||'',patternDetectedAt:new Date().toISOString()};}
function candidate(name,dir,status,conf,score,extra={}){return out(name,dir,status,conf,score,extra);}
function scoreCandidate(c){const status=String(c?.patternStatus||'').toUpperCase();return num(c?.patternConfidence)+(num(c?.patternScore)*4)+(status==='BREAKOUT'||status==='CONFIRMED'?20:status==='FORMED'?10:0);}
function choose(candidates){const valid=candidates.filter(Boolean).filter(x=>x.chartPattern&&x.chartPattern!=='NONE'&&num(x.patternConfidence)>0);if(!valid.length)return out('NONE','NEUTRAL','NONE',0,0,{description:'No reliable chart pattern detected.'});return valid.sort((a,b)=>scoreCandidate(b)-scoreCandidate(a))[0];}
function detectCandlestick(c){if(c.length<3)return null;const a=c[c.length-3],b=c[c.length-2],x=c[c.length-1],br=body(x),rr=candleRange(x),pb=body(b),bull=x.close>x.open,bear=x.close<x.open;
if(bull&&b.close<b.open&&x.open<=b.close&&x.close>=b.open&&br>pb*1.05)return candidate('Bullish Engulfing','BULLISH','FORMED',82,6,{breakoutLevel:x.high,invalidationLevel:x.low,target:x.high+rr*.5,description:'Latest bullish candle engulfs the prior bearish candle.'});
if(bear&&b.close>b.open&&x.open>=b.close&&x.close<=b.open&&br>pb*1.05)return candidate('Bearish Engulfing','BEARISH','FORMED',82,6,{breakoutLevel:x.low,invalidationLevel:x.high,target:x.low-rr*.5,description:'Latest bearish candle engulfs the prior bullish candle.'});
if(br/rr<=.18&&upperWick(x)<=rr*.25&&lowerWick(x)<=rr*.25)return candidate('Doji','NEUTRAL','FORMED',72,3,{breakoutLevel:x.high,invalidationLevel:x.low,target:(x.high+x.low)/2,description:'Small real body relative to the full candle range.'});
if(lowerWick(x)>=br*2&&upperWick(x)<=Math.max(br*.6,rr*.12)&&br/rr<=.45)return candidate('Hammer','BULLISH','FORMED',76,4,{breakoutLevel:x.high,invalidationLevel:x.low,target:x.high+rr*.5,description:'Long lower wick with a small body suggests rejection of lower prices.'});
if(upperWick(x)>=br*2&&lowerWick(x)<=Math.max(br*.6,rr*.12)&&br/rr<=.45)return candidate('Shooting Star','BEARISH','FORMED',76,4,{breakoutLevel:x.low,invalidationLevel:x.high,target:x.low-rr*.5,description:'Long upper wick with a small body suggests rejection of higher prices.'});
if(a.close<a.open&&b.close>b.open&&x.close>b.open&&b.close>(a.open+a.close)/2&&b.open<a.close)return candidate('Morning Star','BULLISH','FORMED',84,6,{breakoutLevel:x.high,invalidationLevel:a.low,target:x.high+(x.high-a.low)*.5,description:'Three-candle bullish reversal structure.'});
if(a.close>a.open&&b.close<b.open&&x.close<b.open&&b.close<(a.open+a.close)/2&&b.open>a.close)return candidate('Evening Star','BEARISH','FORMED',84,6,{breakoutLevel:x.low,invalidationLevel:a.high,target:x.low-(a.high-x.low)*.5,description:'Three-candle bearish reversal structure.'});
if(a.close<a.open&&b.close>b.open&&b.open<a.close&&b.close>a.open&&x.close>x.open)return candidate('Piercing Pattern','BULLISH','FORMED',78,4,{breakoutLevel:x.high,invalidationLevel:a.low,target:x.high+(x.high-a.low)*.4,description:'Bullish reversal sequence with recovery into the prior bearish candle.'});
if(a.close>a.open&&b.close<b.open&&b.open>a.close&&b.close<a.open&&x.close<x.open)return candidate('Dark Cloud Cover','BEARISH','FORMED',78,4,{breakoutLevel:x.low,invalidationLevel:a.high,target:x.low-(a.high-x.low)*.4,description:'Bearish reversal sequence with a close deep into the prior bullish candle.'});
return null;}
function detectStructures(c){const recent=c.slice(-20),earlier=c.slice(-40,-20),all=c.slice(-80),sw=swings(all),rh=sw.h.slice(-5),rl=sw.lo.slice(-5),rr=range(recent),er=range(earlier),last=c[c.length-1],avgVol=avg(recent.map(x=>x.volume).filter(v=>v>0)),volBreak=avgVol>0&&last.volume>=avgVol*1.2,cs=[];
if(earlier.length>=10){const recentPct=pct(rr.high,rr.low),priorPct=pct(er.high,er.low),up=earlier[earlier.length-1].close>earlier[0].close*1.05,down=earlier[earlier.length-1].close<earlier[0].close*.95;if(up&&recentPct>=0&&recentPct<Math.max(priorPct,0.001)*.65)cs.push(candidate('Bull Flag','BULLISH',last.close>=rr.high&&volBreak?'BREAKOUT':'BUILDING',last.close>=rr.high&&volBreak?91:78,last.close>=rr.high&&volBreak?9:5,{breakoutLevel:rr.high,invalidationLevel:rr.low,target:rr.high+(rr.high-rr.low),description:'Strong prior advance followed by contracting consolidation.'}));if(down&&recentPct>=0&&recentPct<Math.max(priorPct,0.001)*.65)cs.push(candidate('Bear Flag','BEARISH',last.close<=rr.low&&volBreak?'BREAKOUT':'BUILDING',last.close<=rr.low&&volBreak?91:78,last.close<=rr.low&&volBreak?9:5,{breakoutLevel:rr.low,invalidationLevel:rr.high,target:rr.low-(rr.high-rr.low),description:'Strong prior decline followed by contracting consolidation.'}));}
if(rh.length>=2&&rl.length>=2){const h1=rh[rh.length-2],h2=rh[rh.length-1],l1=rl[rl.length-2],l2=rl[rl.length-1];if(near(h1,h2)&&l2>l1*1.01){const level=(h1+h2)/2,ok=last.close>level;cs.push(candidate('Ascending Triangle','BULLISH',ok?'CONFIRMED':'BUILDING',ok?92:80,ok?9:5,{breakoutLevel:level,invalidationLevel:l1,target:level+(level-l1),description:'Flat resistance with rising swing lows.'}));}if(near(l1,l2)&&h2<h1*.99){const level=(l1+l2)/2,ok=last.close<level;cs.push(candidate('Descending Triangle','BEARISH',ok?'CONFIRMED':'BUILDING',ok?92:80,ok?9:5,{breakoutLevel:level,invalidationLevel:h1,target:level-(h1-level),description:'Flat support with falling swing highs.'}));}if(near(rl[0],rl[rl.length-1])&&rh.length>=2){const neckline=Math.max(...rh),ok=last.close>neckline;cs.push(candidate('Double Bottom','BULLISH',ok?'CONFIRMED':'FORMED',ok?93:81,ok?9:5,{breakoutLevel:neckline,invalidationLevel:Math.min(...rl),target:neckline+(neckline-Math.min(...rl)),description:'Two comparable swing lows with an intervening neckline.'}));}if(near(rh[0],rh[rh.length-1])&&rl.length>=2){const neckline=Math.min(...rl),ok=last.close<neckline;cs.push(candidate('Double Top','BEARISH',ok?'CONFIRMED':'FORMED',ok?93:81,ok?9:5,{breakoutLevel:neckline,invalidationLevel:Math.max(...rh),target:neckline-(Math.max(...rh)-neckline),description:'Two comparable swing highs with an intervening neckline.'}));}if(rh.length>=3&&rl.length>=2){const head=rh[rh.length-2],left=rh[rh.length-3],right=rh[rh.length-1],neck=Math.min(rl[rl.length-2],rl[rl.length-1]);if(head>left*1.02&&head>right*1.02&&near(left,right,.04)){const ok=last.close<neck;cs.push(candidate('Head and Shoulders','BEARISH',ok?'CONFIRMED':'FORMED',ok?94:83,ok?9:6,{breakoutLevel:neck,invalidationLevel:head,target:neck-(head-neck),description:'Three-peak reversal structure with a higher central head.'}));}}if(rh.length>=2&&rl.length>=3){const head=rl[rl.length-2],left=rl[rl.length-3],right=rl[rl.length-1],neck=Math.max(rh[rh.length-2],rh[rh.length-1]);if(head<left*.98&&head<right*.98&&near(left,right,.04)){const ok=last.close>neck;cs.push(candidate('Inverse Head and Shoulders','BULLISH',ok?'CONFIRMED':'FORMED',ok?94:83,ok?9:6,{breakoutLevel:neck,invalidationLevel:head,target:neck+(neck-head),description:'Three-trough reversal structure with a lower central head.'}));}}}
const hs=slope(rh),ls=slope(rl);if(hs>0&&ls>0){if(Math.abs(hs-ls)/Math.max(Math.abs(hs),Math.abs(ls),1e-9)<.45)cs.push(candidate('Rising Channel','BULLISH','BUILDING',74,4,{breakoutLevel:rr.high,invalidationLevel:rr.low,target:rr.high+(rr.high-rr.low)*.5,description:'Parallel rising swing boundaries.'}));if(ls>hs*1.2)cs.push(candidate('Rising Wedge','BEARISH','BUILDING',77,4,{breakoutLevel:rr.low,invalidationLevel:rr.high,target:rr.low-(rr.high-rr.low)*.5,description:'Both boundaries rise, with support rising faster than resistance.'}));}
if(hs<0&&ls<0){if(Math.abs(hs-ls)/Math.max(Math.abs(hs),Math.abs(ls),1e-9)<.45)cs.push(candidate('Falling Channel','BEARISH','BUILDING',74,4,{breakoutLevel:rr.low,invalidationLevel:rr.high,target:rr.low-(rr.high-rr.low)*.5,description:'Parallel falling swing boundaries.'}));if(Math.abs(hs)>Math.abs(ls)*1.2)cs.push(candidate('Falling Wedge','BULLISH','BUILDING',77,4,{breakoutLevel:rr.high,invalidationLevel:rr.low,target:rr.high+(rr.high-rr.low)*.5,description:'Both boundaries fall, with resistance falling faster than support.'}));}
const compression=rr.low>0&&(rr.high-rr.low)/rr.low<=.08;if(compression){const upBreak=last.close>=rr.high&&volBreak,downBreak=last.close<=rr.low&&volBreak;cs.push(candidate('Rectangle',upBreak?'BULLISH':downBreak?'BEARISH':'NEUTRAL',upBreak||downBreak?'BREAKOUT':'BUILDING',upBreak||downBreak?88:70,upBreak||downBreak?8:3,{breakoutLevel:upBreak?rr.high:rr.low,invalidationLevel:upBreak?rr.low:rr.high,target:upBreak?rr.high+(rr.high-rr.low):rr.low-(rr.high-rr.low),description:'Horizontal consolidation/range structure.'}));}
if(c.length>=50){const first=c.slice(-50,-25),middle=c.slice(-25,-10),handle=c.slice(-10),r1=range(first),r2=range(middle),rh2=range(handle);if(r1.high>0&&r2.low<r1.high*.95&&r2.high>r1.high*.95&&rh2.high<r2.high*1.03){const ok=last.close>rh2.high;cs.push(candidate('Cup and Handle','BULLISH',ok?'BREAKOUT':'BUILDING',ok?90:78,ok?8:5,{breakoutLevel:rh2.high,invalidationLevel:rh2.low,target:rh2.high+(r1.high-r2.low),description:'Rounded recovery followed by a shallow handle.'}));}}
return cs;}
function detectChartPattern(input){const c=candlesOf(input);if(c.length<20)return out('NONE','NEUTRAL','NONE',0,0,{description:'Insufficient candles for reliable pattern detection.'});const candidates=[];const candle=detectCandlestick(c);if(candle)candidates.push(candle);candidates.push(...detectStructures(c));return choose(candidates);}
module.exports={detectChartPattern};
