require("dotenv").config();

const DASHBOARD_MIN_SCORE = 80;
const DASHBOARD_FALLBACK_ROWS = 5;

module.exports = {
    BROKER: (process.env.BROKER || "UPSTOX").trim().toUpperCase(),
    UPSTOX: { ACCESS_TOKEN: process.env.UPSTOX_ACCESS_TOKEN || "" },
    ANGELONE: { API_KEY: process.env.API_KEY || "", CLIENT_ID: process.env.CLIENT_ID || "", MPIN: process.env.MPIN || "", TOTP_SECRET: process.env.TOTP_SECRET || "" },
    API_KEY: process.env.API_KEY || "",
    CLIENT_ID: process.env.CLIENT_ID || "",
    MPIN: process.env.MPIN || "",
    TOTP_SECRET: process.env.TOTP_SECRET || "",
    GOOGLE_SHEET_URL: process.env.GOOGLE_SHEET_URL || "",
    SCANNER_UNIVERSE: (process.env.SCANNER_UNIVERSE || "NIFTY500").trim().toUpperCase(),
    BANKNIFTY_ENABLED: true,
    BANKNIFTY_SYMBOL: "BANKNIFTY",
    BANKNIFTY_FULL_CONSTITUENTS: true,
    TOP_LIVE_STOCKS: 20,
    ONE_ACTIVE_TRADE: true,
    MAX_STOCKS: 0,
    EMA_PERIODS: [5, 9, 20, 50, 100, 200],
    EMA_SHORT: 20,
    EMA_LONG: 200,
    RSI_PERIOD: 14,
    MACD: { FAST: 12, SLOW: 26, SIGNAL: 9 },
    ADX_PERIOD: 14,
    ATR_PERIOD: 14,
    SUPERTREND: { ATR_PERIOD: 10, MULTIPLIER: 3 },
    BOLLINGER: { PERIOD: 20, STD_DEV: 2 },
    THRESHOLDS: { AI_BUY_SCORE: 85, AI_SELL_SCORE: -85, AI_WATCH_SCORE: 60, DASHBOARD_MIN_SCORE, DASHBOARD_MAX_ROWS: DASHBOARD_FALLBACK_ROWS, MIN_CONFIDENCE: 70, MIN_RR: 1.5, PRE_SCORE_MIN: 0, DAILY_CANDLE_MIN: 50, MAX_QUALIFIED_STOCKS: 20 },
    AI_BUY_SCORE: 85,
    AI_SELL_SCORE: -85,
    AI_WATCH_SCORE: 60,
    DASHBOARD_MIN_SCORE,
    DASHBOARD_MAX_ROWS: DASHBOARD_FALLBACK_ROWS,
    DASHBOARD_FALLBACK_ROWS,
    SCHEDULER: { TIMEZONE: "Asia/Kolkata", START_HOUR: 9, START_MINUTE: 10, END_HOUR: 15, END_MINUTE: 30, INTERVAL_MINUTES: 30, TIMEOUT_MINUTES: 420 }
};
