const DIVIDEND_LONG_TERM_SYMBOLS=[
  "ITC","TCS","POWERGRID","COALINDIA","REC","PFC","ONGC","WIPRO","INFY","IOC",
  "BPCL","HINDZINC","NMDC","GAIL","NTPC","VEDL","HINDPETRO","RITES","DRREDDY","HCLTECH"
];
module.exports={DIVIDEND_LONG_TERM_SYMBOLS};
