// ============================================================
// AI SMART SCANNER — GOOGLE SHEET UPLOADER
// ============================================================
const axios=require('axios');
const config=require('./config');
const {calculateOIMoodForStock}=require('./oiMood');
const DASHBOARD_MIN_ROWS=5;
const DASHBOARD_SCORE=Number(config.THRESHOLDS?.DASHBOARD_MIN_SCORE??config.DASHBOARD_MIN_SCORE??80);
const MIN_CONFIDENCE=Number(config.THRESHOLDS?.MIN_CONFIDENCE??70);
const MIN_RR=Number(config.THRESHOLDS?.MIN_RR??1.5);
const REQUIRED_OI_HEADERS=['oiMood','oiSentiment','oiDataAvailable','oiPriceChangePercent','oiChangePercent'];
const DASHBOARD_HEADERS=['stockPrice','symbol','optionType','entryPrice','bestStrike','optionLTP','confidence','target','stopLoss','oiMood'];
const ACCURACY_HEADERS=['recordId','predictionTime','symbol','stockPrice','optionType','confidence','predictedEntry','target','stopLoss','currentPrice','targetSLReached','slReason','resultTime','resultPrice','accuracyPercent'];
const GOOGLE_TIMEOUT=120000;
function getGoogleSheetUrl(){return process.env.GOOGLE_SHEET_WEBHOOK_URL||process.env.GOOGLE_SCRIPT_URL||process.env.GOOGLE_SHEETS_WEBHOOK_URL||process.env.GOOGLE_SHEET_URL||process.env.GOOGLE_APPS_SCRIPT_URL||config.GOOGLE_SHEET_WEBHOOK_URL||config.GOOGLE_SCRIPT_URL||config.GOOGLE_SHEETS_WEBHOOK_URL||config.GOOGLE_SHEET_URL||config.GOOGLE_APPS_SCRIPT_URL||null;}
function n(v){const x=Number(v);return Number.isFinite(x)?x:null;}
function score(r={}){return n(r.finalScore??r.rankingScore??r.aiFinalScore??r.score??r.scannerScore)??0;}
function magnitude(r={}){return Math.min(100,Math.abs(score(r)));}
function direction(r={}){const d=String(r.direction??r.finalDirection??r.optionType??'').trim().toUpperCase();if(['CALL','CE','BUY','BULLISH','UP','LONG'].includes(d))return'BULLISH';if(['PUT','PE','SELL','BEARISH','DOWN','SHORT'].includes(d))return'BEARISH';return'SIDEWAYS';}
function optionType(r={}){const v=String(r.optionType??r.optionSymbol??'').toUpperCase();if(v.includes('PUT')||v==='PE'||v.includes(' PE'))return'PE';if(v.includes('CALL')||v==='CE'||v.includes(' CE'))return'CE';return direction(r)==='BEARISH'?'PE':direction(r)==='BULLISH'?'CE':'';}
function addOIMood(r={}){const x=r&&typeof r==='object'?r:{};let m=null;try{m=calculateOIMoodForStock(x);}catch(_){ }return{...x,oiMood:String(x.oiMood??x.OIMood??x.oi_mood??m?.mood??'UNKNOWN').trim()||'UNKNOWN',oiSentiment:String(x.oiSentiment??x.OISentiment??m?.sentiment??'UNKNOWN').trim()||'UNKNOWN',oiDataAvailable:m?.dataAvailable===true||x.oiDataAvailable===true,oiPriceChangePercent:n(x.oiPriceChangePercent??m?.priceChangePercent)??0,oiChangePercent:n(x.oiChangePercent??m?.oiChangePercent)??0};}
function selectDashboardRows(rows=[]){const list=(Array.isArray(rows)?rows:[]).filter(Boolean).map(addOIMood).filter(r=>direction(r)!=='SIDEWAYS');const above=list.filter(r=>magnitude(r)>=DASHBOARD_SCORE);const pool=above.length?above:list.slice(0,DASHBOARD_MIN_ROWS);return pool.sort((a,b)=>{const ds=magnitude(b)-magnitude(a);if(ds)return ds;return(n(b.confidence)??0)-(n(a.confidence)??0);});}
function dashboardRow(r={}){return{stockPrice:n(r.stockPrice??r.price??r.livePrice??r.currentPrice??r.ltp),symbol:String(r.symbol??r.stock??r.tradingSymbol??'').trim(),optionType:optionType(r),entryPrice:n(r.stockEntry??r.underlyingEntry??r.marketEntry??r.entry??r.stockPrice??r.price??r.currentPrice),bestStrike:n(r.recommendedStrike??r.optionStrike??r.atmStrike),optionLTP:n(r.optionPremiumEntry??r.optionLTP??r.optionEntry),confidence:n(r.optionsConfidence??r.confidence),target:n(r.stockTarget1??r.target1??r.target),stopLoss:n(r.stockStopLoss??r.stopLoss),oiMood:String(r.oiMood??'UNKNOWN')};}
function clean(v){if(v==null)return'';if(typeof v==='number')return Number.isFinite(v)?v:'';if(typeof v==='boolean')return v;if(typeof v==='object'){try{return JSON.stringify(v);}catch(_){return String(v);}}return String(v);}
function toIST(v){if(!v)return'';const d=v instanceof Date?new Date(v.getTime()):new Date(v);if(Number.isNaN(d.getTime()))return String(v);const p=new Intl.DateTimeFormat('en-IN',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(d).reduce((o,x)=>(o[x.type]=x.value,o),{});return `${p.year}-${p.month}-${p.day} ${p.hour}:${p.minute}:${p.second} IST`;}
function buildSheetPayload(sheet,objects=[]){const rows=(Array.isArray(objects)?objects:[]).filter(Boolean).map(addOIMood),headers=[];const seen=new Set();REQUIRED_OI_HEADERS.forEach(h=>{seen.add(h);headers.push(h);});rows.forEach(r=>Object.keys(r).forEach(k=>{if(!seen.has(k)){seen.add(k);headers.push(k);}}));return{action:'replaceSheet',sheet,clearFirst:true,headers,rows:rows.map(r=>headers.map(h=>h==='score'||h==='finalScore'||h==='rankingScore'||h==='aiFinalScore'?Math.max(-100,Math.min(100,Number(r[h])||0)):clean(r[h]))),timestamp:new Date().toISOString()};}
function buildDashboardPayload(rows=[]){const selected=selectDashboardRows(rows).map(dashboardRow);return{action:'replaceSheet',sheet:'Dashboard',clearFirst:true,headers:DASHBOARD_HEADERS,rows:selected.map(r=>DASHBOARD_HEADERS.map(h=>clean(r[h]))),timestamp:new Date().toISOString()};}
async function postToGoogleSheet(payload){const url=getGoogleSheetUrl();if(!url)throw new Error('Google Sheet webhook URL is not configured');return axios.post(url,payload,{timeout:GOOGLE_TIMEOUT,headers:{'Content-Type':'application/json'}});}
async function postReplaceSheet(sheet,objects){const r=await postToGoogleSheet(buildSheetPayload(sheet,objects));if(r?.data?.success===false)throw new Error(`Google Sheets rejected ${sheet}: ${r.data.error||'unknown error'}`);return r?.data||{};}
async function postDashboard(rows){const r=await postToGoogleSheet(buildDashboardPayload(rows));if(r?.data?.success===false)throw new Error(`Google Sheets rejected Dashboard: ${r.data.error||'unknown error'}`);return r?.data||{};}
function buildAccuracyRow(r={}){return{recordId:String(r.recordId??r.predictionId??`${r.symbol||r.stock||'UNKNOWN'}_${Date.now()}`),predictionTime:toIST(r.predictionTime||r.accuracyPredictionTime||r.timestamp||new Date()),symbol:String(r.symbol??r.stock??r.tradingSymbol??''),stockPrice:n(r.stockPrice??r.price??r.currentPrice),optionType:optionType(r),confidence:n(r.optionsConfidence??r.confidence),predictedEntry:n(r.predictedEntry??r.stockEntry??r.underlyingEntry??r.marketEntry??r.entry),target:n(r.predictedTarget1??r.stockTarget1??r.target1??r.target),stopLoss:n(r.predictedStopLoss??r.stockStopLoss??r.stopLoss),currentPrice:n(r.livePrice??r.currentPrice??r.ltp??r.price),targetSLReached:String(r.targetSLReached??'PENDING').toUpperCase(),slReason:String(r.slReason??''),resultTime:toIST(r.resultTime),resultPrice:n(r.resultPrice),accuracyPercent:n(r.accuracyPercent)};}
async function postAccuracyRows(rows=[]){const list=(Array.isArray(rows)?rows:[]).filter(Boolean);if(!list.length)return{success:true,rowCount:0};const e=list.map(buildAccuracyRow);const r=await postToGoogleSheet({action:'appendRows',sheet:'ACCURACY',headers:ACCURACY_HEADERS,rows:e.map(x=>ACCURACY_HEADERS.map(h=>clean(x[h]))),timestamp:new Date().toISOString()});if(r?.data?.success===false)throw new Error(`Google Sheets rejected ACCURACY: ${r.data.error||'unknown error'}`);return r?.data||{};}
async function updateGoogleSheet(payload={}){if(String(payload.action||'').trim()==='scanner_status'){const r=await postToGoogleSheet({action:'scanner_status',scannerStatus:payload.scannerStatus||payload.status||{}});if(r?.data?.success===false)throw new Error(r.data.error||'SCANNER_STATUS rejected');return r?.data||{};}const scannerData=Array.isArray(payload.scannerData)?payload.scannerData:[],dashboardData=Array.isArray(payload.dashboardData)?payload.dashboardData:[],accuracyData=Array.isArray(payload.accuracyData)?payload.accuracyData:[];const scanner=await postReplaceSheet('SCANNER',scannerData);const dashboard=await postDashboard(dashboardData);const accuracy=await postAccuracyRows(accuracyData);return{success:true,scanner,dashboard,accuracy,scannerRows:scannerData.length,dashboardRows:selectDashboardRows(dashboardData).length,accuracyRows:accuracyData.length};}
function buildScannerStatus(x={}){const now=new Date();return{status:String(x.status||'SUCCESS').toUpperCase(),lastScanTime:now.toISOString(),lastScanTimeIST:toIST(now),lastScanSource:process.env.GITHUB_ACTIONS?'GitHub Actions':'Local',broker:String(x.broker||process.env.BROKER||'UPSTOX').toUpperCase(),universe:String(x.universe||'ALL').toUpperCase(),stocksScanned:Number(x.scanned)||0,successfulScans:Number(x.successfulScans)||0,failedScans:Number(x.failedScans)||0,callCandidates:Number(x.callCandidates)||0,putCandidates:Number(x.putCandidates)||0,tradeCount:Number(x.tradeCount)||0,watchCount:Number(x.watchCount)||0,rejectCount:Number(x.rejectCount)||0,elapsedSeconds:Number(x.elapsedSeconds)||0,durationMs:Number(x.durationMs)||0};}
module.exports={updateGoogleSheet,postToGoogleSheet,getGoogleSheetUrl,selectDashboardRows,score,magnitude,direction,buildAccuracyRow,postAccuracyRows,buildScannerStatus,DASHBOARD_MAX_ROWS:DASHBOARD_MIN_ROWS,MIN_CONFIDENCE,MIN_RR,addOIMood,buildDashboardPayload,postDashboard,ACCURACY_HEADERS};