const { EMA,SMA,RSI,MACD,BollingerBands,ATR,ADX,OBV,MFI }=require('technicalindicators');
const { calculateSupertrend }=require('./supertrend');
const MIN_CANDLES=2, RVOL_SPIKE_THRESHOLD=1.5;
function safe(v,f=null){const n=Number(v);return Number.isFinite(n)?n:f;}
function last(v,f=null){return Array.isArray(v)&&v.length?v[v.length-1]:f;}
function calc(fn,f=null){try{return last(fn(),f);}catch(_){return f;}}
function valid(c){if(!c||typeof c!=='object')return false;const h=Number(c.high),l=Number(c.low),cl=Number(c.close),v=c.volume==null||c.volume===''?0:Number(c.volume);return Number.isFinite(h)&&Number.isFinite(l)&&Number.isFinite(cl)&&Number.isFinite(v)&&h>0&&l>0&&cl>0&&h>=l&&cl>=l&&cl<=h&&v>=0;}
function normalize(cs){return cs.map(c=>({...c,high:Number(c.high),low:Number(c.low),close:Number(c.close),volume:Math.max(0,Number(c.volume||0))}));}
function empty(){return {ema5:null,ema9:null,ema20:null,ema50:null,ema100:null,ema200:null,rsi:null,macd:null,bollinger:null,atr:null,adx:null,volume:0,volumeSMA20:null,rvol:null,volumeSpike:false,obv:null,mfi:null,vwap:null,supertrend:null};}
function istDate(value){const d=new Date(value);if(Number.isNaN(d.getTime()))return '';return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);}
function calculateSessionVWAP(candles,sessionDate){if(!Array.isArray(candles)||!candles.length)return null;let day=sessionDate;if(!day){const t=candles[candles.length-1]?.time??candles[candles.length-1]?.timestamp??candles[candles.length-1]?.datetime;if(t)day=istDate(t);}let tpv=0,vol=0;for(const c of candles){if(!valid(c))continue;const t=c.time??c.timestamp??c.datetime??c.date;if(day&&t&&istDate(t)!==day)continue;const v=Number(c.volume||0);if(v<=0)continue;tpv+=((Number(c.high)+Number(c.low)+Number(c.close))/3)*v;vol+=v;}return vol>0?tpv/vol:safe(candles[candles.length-1]?.close);}
function calculateIndicators(candles){if(!Array.isArray(candles)||candles.length<MIN_CANDLES||!candles.every(valid))return empty();const c=normalize(candles),close=c.map(x=>x.close),high=c.map(x=>x.high),low=c.map(x=>x.low),volume=c.map(x=>x.volume);const ema=p=>close.length>=p?calc(()=>EMA.calculate({period:p,values:close})):null;const e5=ema(5),e9=ema(9),e20=ema(20),e50=ema(50),e100=ema(100),e200=ema(200);const rsi=close.length>=15?calc(()=>RSI.calculate({period:14,values:close})):null;const macd=close.length>=35?calc(()=>MACD.calculate({values:close,fastPeriod:12,slowPeriod:26,signalPeriod:9,SimpleMAOscillator:false,SimpleMASignal:false})):null;const bollinger=close.length>=20?calc(()=>BollingerBands.calculate({period:20,stdDev:2,values:close})):null;const atr=close.length>=15?calc(()=>ATR.calculate({high,low,close,period:14})):null;const adx=close.length>=30?calc(()=>ADX.calculate({high,low,close,period:14})):null;const latestVolume=safe(volume.at(-1),0),volumeSMA20=volume.length>=20?calc(()=>SMA.calculate({period:20,values:volume})):null;const rvol=Number.isFinite(latestVolume)&&Number.isFinite(volumeSMA20)&&volumeSMA20>0?Number((latestVolume/volumeSMA20).toFixed(2)):null;const obv=close.length>=2?calc(()=>OBV.calculate({close,volume})):null;const mfi=close.length>=15?calc(()=>MFI.calculate({high,low,close,volume,period:14})):null;let supertrend=null;try{if(c.length>=15)supertrend=calculateSupertrend(c);}catch(_){}return {ema5:safe(e5),ema9:safe(e9),ema20:safe(e20),ema50:safe(e50),ema100:safe(e100),ema200:safe(e200),rsi:safe(rsi),macd:macd&&typeof macd==='object'?{MACD:safe(macd.MACD),signal:safe(macd.signal),histogram:safe(macd.histogram)}:null,bollinger,atr:safe(atr),adx:adx&&typeof adx==='object'?{adx:safe(adx.adx),pdi:safe(adx.pdi),mdi:safe(adx.mdi)}:safe(adx),volume:latestVolume,volumeSMA20:safe(volumeSMA20),rvol,volumeSpike:Number.isFinite(rvol)&&rvol>=RVOL_SPIKE_THRESHOLD,obv:safe(obv),mfi:safe(mfi),vwap:safe(calculateSessionVWAP(c)),supertrend};}
module.exports=calculateIndicators;module.exports.calculateIndicators=calculateIndicators;module.exports.calculateVWAP=calculateSessionVWAP;module.exports.calculateSessionVWAP=calculateSessionVWAP;module.exports.isValidCandle=valid;
