const { EMA,SMA,RSI,MACD,BollingerBands,ATR,ADX,OBV,MFI }=require('technicalindicators');
const { calculateSupertrend }=require('./supertrend');
const MIN_CANDLES=2,RVOL_SPIKE_THRESHOLD=1.5;
const n=v=>{const x=Number(v);return Number.isFinite(x)?x:null};
const last=(a,d=null)=>Array.isArray(a)&&a.length?a[a.length-1]:d;
const calc=(fn,d=null)=>{try{return last(fn(),d)}catch(_){return d}};
function valid(c){if(!c||typeof c!=='object')return false;const o=n(c.open??c.close),h=n(c.high),l=n(c.low),cl=n(c.close),v=c.volume==null||c.volume===''?0:n(c.volume);return [o,h,l,cl,v].every(Number.isFinite)&&o>0&&h>0&&l>0&&cl>0&&h>=Math.max(o,cl)&&l<=Math.min(o,cl)&&v>=0}
function normalize(a){return(Array.isArray(a)?a:[]).filter(valid).map(c=>({...c,open:n(c.open??c.close),high:n(c.high),low:n(c.low),close:n(c.close),volume:Math.max(0,n(c.volume)||0)}))}
function empty(){return{ema5:null,ema9:null,ema20:null,ema50:null,ema100:null,ema200:null,rsi:null,macd:null,bollinger:null,atr:null,adx:null,volume:0,volumeSMA20:null,rvol:null,volumeSpike:false,obv:null,mfi:null,vwap:null,supertrend:null,dataQuality:{validCandles:0,partial:true}}}
function istDate(v){const d=new Date(v);if(Number.isNaN(d.getTime()))return'';return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(d)}
function calculateSessionVWAP(a,sessionDate){if(!Array.isArray(a)||!a.length)return null;let day=sessionDate;if(!day){const t=a.at(-1)?.time??a.at(-1)?.timestamp??a.at(-1)?.datetime??a.at(-1)?.date;if(t)day=istDate(t)}let tpv=0,vol=0;for(const c of a){if(!valid(c))continue;const t=c.time??c.timestamp??c.datetime??c.date;if(day&&t&&istDate(t)!==day)continue;const v=n(c.volume)||0;if(v<=0)continue;tpv+=((n(c.high)+n(c.low)+n(c.close))/3)*v;vol+=v}return vol>0?tpv/vol:n(a.at(-1)?.close)}
function calculateIndicators(candles){const c=normalize(candles);if(c.length<MIN_CANDLES)return empty();const close=c.map(x=>x.close),high=c.map(x=>x.high),low=c.map(x=>x.low),volume=c.map(x=>x.volume);const ema=p=>close.length>=p?calc(()=>EMA.calculate({period:p,values:close})):null;const e5=ema(5),e9=ema(9),e20=ema(20),e50=ema(50),e100=ema(100),e200=ema(200);const rsi=close.length>=15?calc(()=>RSI.calculate({period:14,values:close})):null;const macd=close.length>=35?calc(()=>MACD.calculate({values:close,fastPeriod:12,slowPeriod:26,signalPeriod:9,SimpleMAOscillator:false,SimpleMASignal:false})):null;const bollinger=close.length>=20?calc(()=>BollingerBands.calculate({period:20,stdDev:2,values:close})):null;const atr=close.length>=15?calc(()=>ATR.calculate({high,low,close,period:14})):null;const adx=close.length>=30?calc(()=>ADX.calculate({high,low,close,period:14})):null;const latestVolume=n(volume.at(-1))||0,volumeSMA20=volume.length>=20?calc(()=>SMA.calculate({period:20,values:volume})):null;const rvol=Number.isFinite(latestVolume)&&Number.isFinite(volumeSMA20)&&volumeSMA20>0?Number((latestVolume/volumeSMA20).toFixed(2)):null;const obv=close.length>=2?calc(()=>OBV.calculate({close,volume})):null;const mfi=close.length>=15?calc(()=>MFI.calculate({high,low,close,volume,period:14})):null;let supertrend=null;try{if(c.length>=15)supertrend=calculateSupertrend(c)}catch(_){}return{ema5:n(e5),ema9:n(e9),ema20:n(e20),ema50:n(e50),ema100:n(e100),ema200:n(e200),rsi:n(rsi),macd:macd&&typeof macd==='object'?{MACD:n(macd.MACD),signal:n(macd.signal),histogram:n(macd.histogram)}:null,bollinger:bollinger&&typeof bollinger==='object'?{upper:n(bollinger.upper),middle:n(bollinger.middle),lower:n(bollinger.lower)}:null,atr:n(atr),adx:adx&&typeof adx==='object'?{adx:n(adx.adx),pdi:n(adx.pdi),mdi:n(adx.mdi)}:null,volume:latestVolume,volumeSMA20:n(volumeSMA20),rvol,volumeSpike:Number.isFinite(rvol)&&rvol>=RVOL_SPIKE_THRESHOLD,obv:n(obv),mfi:n(mfi),vwap:n(calculateSessionVWAP(c)),supertrend,dataQuality:{validCandles:c.length,ema200Available:c.length>=200,adxAvailable:c.length>=30,rsiAvailable:c.length>=15,macdAvailable:c.length>=35,volumeAvailable:c.some(x=>x.volume>0),partial:c.length<220}}}
module.exports=calculateIndicators;module.exports.calculateIndicators=calculateIndicators;module.exports.calculateVWAP=calculateSessionVWAP;module.exports.calculateSessionVWAP=calculateSessionVWAP;module.exports.isValidCandle=valid;
