const axios=require("axios");
const UPSTOX_BASE="https://api.upstox.com";
const MAX_TOP_STOCKS=20;
const TOP_NSE_STOCKS=500;
const TOP_OPTION_STOCKS=100;
const MIN_VOLUME=1;
const MIN_OI=1;
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f;}
function normalizeQuoteMap(data){const out=[];for(const[key,value]of Object.entries(data||{})){if(!value||typeof value!=="object")continue;out.push({instrumentKey:value.instrument_token||value.instrumentKey||key,symbol:value.symbol||"",price:n(value.last_price??value.lastPrice),volume:n(value.volume??value.volume_traded??value.volumeTraded),oi:n(value.oi??value.open_interest??value.openInterest),previousOI:n(value.prev_oi??value.previous_oi??value.previousOI),oiDayHigh:n(value.oi_day_high),oiDayLow:n(value.oi_day_low),timestamp:value.timestamp||null,lastTradeTime:value.last_trade_time||value.lastTradeTime||null,raw:value});}return out;}
async function upstoxFullQuotes(instrumentKeys){const token=process.env.UPSTOX_ACCESS_TOKEN;if(!token)throw new Error("UPSTOX_ACCESS_TOKEN is missing");const keys=[...new Set((instrumentKeys||[]).filter(Boolean))];if(!keys.length)return[];const response=await axios.get(`${UPSTOX_BASE}/v2/market-quote/quotes`,{params:{instrument_key:keys.join(",")},headers:{Accept:"application/json",Authorization:`Bearer ${token}`},timeout:15000});return normalizeQuoteMap(response?.data?.data);}
async function resolveEquityKeys(symbols,broker){const rows=[];for(const symbol of symbols){try{const instrument=await broker.getInstrument(symbol);const key=instrument?.instrument_key||instrument?.instrumentKey||null;if(key)rows.push({symbol,key});}catch(_){} }return rows;}
async function rankByLiveVolume(symbols,broker,limit){const source=[...new Set((Array.isArray(symbols)?symbols:[]).map(x=>String(x||"").trim().toUpperCase()).filter(Boolean))];const resolved=await resolveEquityKeys(source,broker);if(!resolved.length)throw new Error("No NSE equity instruments resolved for live-volume ranking");let quotes=[];const chunkSize=450;for(let i=0;i<resolved.length;i+=chunkSize){const chunk=resolved.slice(i,i+chunkSize);const result=await upstoxFullQuotes(chunk.map(x=>x.key));const byKey=new Map(result.map(q=>[q.instrumentKey,q]));for(const item of chunk){const q=byKey.get(item.key);if(q)quotes.push({symbol:item.symbol,instrumentKey:item.key,...q});}}const valid=quotes.filter(q=>q.price>0&&q.volume>=MIN_VOLUME);if(!valid.length)throw new Error("Live market volume unavailable for scanner universe");valid.sort((a,b)=>(b.volume-a.volume)||(b.price-a.price));const top=valid.slice(0,Math.min(limit,valid.length)).map((q,index)=>({...q,liveVolumeRank:index+1,volumeConfirmed:q.volume>=MIN_VOLUME,liveMarketConfirmed:true,liveQuoteTimestamp:q.timestamp||q.lastTradeTime||null}));return{top,allQuotes:valid,universeSize:source.length};}
async function getTop500ByLiveVolume(symbols,broker,limit=TOP_NSE_STOCKS){return rankByLiveVolume(symbols,broker,Math.min(TOP_NSE_STOCKS,Math.max(1,limit)));}
async function getTop100OptionStocks(top500Rows,optionEligibleSymbols,limit=TOP_OPTION_STOCKS){const eligible=new Set((Array.isArray(optionEligibleSymbols)?optionEligibleSymbols:[]).map(x=>String(x||"").trim().toUpperCase()).filter(Boolean));const rows=(Array.isArray(top500Rows)?top500Rows:[]).filter(r=>eligible.has(String(r.symbol||"").toUpperCase()));rows.sort((a,b)=>(b.volume-a.volume)||(b.price-a.price));return rows.slice(0,Math.min(TOP_OPTION_STOCKS,Math.max(1,limit))).map((r,index)=>({...r,optionUniverseRank:index+1,optionEligible:true}));}
async function getTop20ByLiveVolume(symbols,broker,limit=MAX_TOP_STOCKS){return rankByLiveVolume(symbols,broker,Math.min(MAX_TOP_STOCKS,Math.max(1,limit)));}
function normalizeExpiry(v){const s=String(v??"").trim();if(!s)return null;if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const d=new Date(s);return Number.isNaN(d.getTime())?null:d.toISOString().slice(0,10);}
function optionType(c){const x=String(c?.instrument_type??c?.option_type??c?.optionType??"").toUpperCase();if(["CE","CALL","C"].includes(x))return"CE";if(["PE","PUT","P"].includes(x))return"PE";const s=String(c?.trading_symbol||c?.tradingsymbol||"").toUpperCase();return s.endsWith("CE")?"CE":s.endsWith("PE")?"PE":null;}
function chooseContract(contracts,direction,spot){const side=direction==="BULLISH"?"CE":"PE",today=new Date();today.setHours(0,0,0,0);const usable=(Array.isArray(contracts)?contracts:[]).filter(c=>{const expiry=normalizeExpiry(c?.expiry??c?.expiry_date),d=expiry?new Date(`${expiry}T00:00:00`):null,days=d&&!Number.isNaN(d.getTime())?Math.ceil((d-today)/86400000):-1;return optionType(c)===side&&days>=7&&n(c?.strike_price??c?.strike)>0&&(c?.instrument_key||c?.instrumentKey);});if(!usable.length)return null;const expiry=[...new Set(usable.map(c=>normalizeExpiry(c?.expiry??c?.expiry_date)).filter(Boolean))].sort()[0],sameExpiry=usable.filter(c=>normalizeExpiry(c?.expiry??c?.expiry_date)===expiry);return sameExpiry.reduce((best,c)=>!best||Math.abs(n(c.strike_price??c.strike)-spot)<Math.abs(n(best.strike_price??best.strike)-spot)?c:best,null);}
async function getOptionConfirmation(row,direction,broker){const symbol=row?.symbol||row?.stock,spot=n(row?.price);if(!symbol||spot<=0||!broker||typeof broker.getOptionContracts!=="function")return{confirmed:false,reason:"OPTION_DATA_API_UNAVAILABLE"};try{const contracts=await broker.getOptionContracts(symbol),contract=chooseContract(contracts,direction,spot);if(!contract)return{confirmed:false,reason:"NO_VALID_OPTION_CONTRACT"};const key=contract.instrument_key||contract.instrumentKey;const quote=(await upstoxFullQuotes([key])).find(q=>q.instrumentKey===key);if(!quote)return{confirmed:false,reason:"LIVE_OPTION_QUOTE_UNAVAILABLE",optionInstrumentKey:key};const volume=n(quote.volume),oi=n(quote.oi),previousOI=n(quote.previousOI),oiChange=previousOI>0?oi-previousOI:0,oiChangePercent=previousOI>0?(oiChange/previousOI)*100:0,confirmed=volume>=MIN_VOLUME&&oi>=MIN_OI;return{confirmed,reason:confirmed?"LIVE_VOLUME_OI_CONFIRMED":"INSUFFICIENT_LIVE_OPTION_VOLUME_OI",optionSymbol:contract.trading_symbol||contract.tradingsymbol||"",optionInstrumentKey:key,optionType:direction==="BULLISH"?"CE":"PE",optionStrike:n(contract.strike_price??contract.strike),optionExpiry:normalizeExpiry(contract.expiry??contract.expiry_date)||"",optionLTP:quote.price,optionVolume:volume,optionOI:oi,optionPreviousOI:previousOI,optionOIChange:oiChange,optionOIChangePercent:oiChangePercent,optionTimestamp:quote.timestamp||null,optionLastTradeTime:quote.lastTradeTime||null};}catch(error){return{confirmed:false,reason:`LIVE_OPTION_CONFIRMATION_ERROR:${error?.message||error}`};}}
module.exports={getTop20ByLiveVolume,getTop500ByLiveVolume,getTop100OptionStocks,getOptionConfirmation,upstoxFullQuotes,MAX_TOP_STOCKS,TOP_NSE_STOCKS,TOP_OPTION_STOCKS};
