const { getBroker }=require('./brokers');
const { calculateIndicators }=require('./indicators');
function emptyTrend(reason='NO_DATA'){return{trend:'UNKNOWN',direction:'UNKNOWN',bullish:false,bearish:false,score:0,bullishPoints:0,bearishPoints:0,valid:false,reason};}
const num=v=>Number.isFinite(Number(v))?Number(v):0;
function normalize(cs){if(!Array.isArray(cs))return[];return cs.map(c=>({time:c?.time??c?.timestamp??c?.datetime??c?.date??c?.[0],open:num(c?.open??c?.[1]),high:num(c?.high??c?.[2]),low:num(c?.low??c?.[3]),close:num(c?.close??c?.[4]),volume:num(c?.volume??c?.[5])})).filter(c=>c.open>0&&c.high>0&&c.low>0&&c.close>0&&c.high>=c.low&&c.high>=c.open&&c.high>=c.close&&c.low<=c.open&&c.low<=c.close).sort((a,b)=>new Date(a.time)-new Date(b.time));}
function direction(v){const s=String(v||'').toUpperCase();return s.includes('BULLISH')?'BULLISH':s.includes('BEARISH')?'BEARISH':'UNKNOWN';}
function calculateTrend(symbol,interval,candles){try{const d=normalize(candles);if(d.length<50)return emptyTrend('INSUFFICIENT_CANDLES');const i=calculateIndicators(d);const e20=num(i.ema20),e50=num(i.ema50),e200=num(i.ema200),rsi=num(i.rsi),m=i.macd||{},macd=num(m.MACD??m.macd),sig=num(m.signal),a=i.adx||{},adx=num(a.adx),pdi=num(a.pdi),mdi=num(a.mdi),last=d.at(-1).close;let b=0,s=0;if(e20&&e50){if(e20>e50)b++;else if(e20<e50)s++;}if(e50&&e200){if(e50>e200)b++;else if(e50<e200)s++;}if(last>e20)b++;else if(last<e20)s++;if(rsi>50)b++;else if(rsi>0&&rsi<50)s++;if(macd>sig)b++;else if(macd<sig)s++;if(adx>=20){if(pdi>mdi)b++;else if(mdi>pdi)s++;}const bull=b>=3&&b>s,bear=s>=3&&s>b,trend=bull?(b>=4?'STRONG BULLISH':'BULLISH'):bear?(s>=4?'STRONG BEARISH':'BEARISH'):'SIDEWAYS';return{trend,direction:direction(trend),bullish:bull,bearish:bear,score:bull?b:-s,bullishPoints:b,bearishPoints:s,valid:true,reason:'OK'};}catch(e){console.log(`⚠️ ${symbol} ${interval} MTF failed: ${e.message}`);return emptyTrend('CALCULATION_ERROR');}}
function bucket4H(candles){const data=normalize(candles),map=new Map();for(const c of data){const d=new Date(c.time);if(Number.isNaN(d.getTime()))continue;const mins=d.getHours()*60+d.getMinutes(),anchor=9*60+15;let offset=mins-anchor;if(offset<0)offset=Math.floor(offset/240)*240;const bucketIndex=Math.floor(offset/240);const start=new Date(d);start.setHours(0,0,0,0);start.setMinutes(anchor+bucketIndex*240);const key=start.toISOString();const x=map.get(key);if(!x)map.set(key,{time:start.toISOString(),open:c.open,high:c.high,low:c.low,close:c.close,volume:c.volume});else{x.high=Math.max(x.high,c.high);x.low=Math.min(x.low,c.low);x.close=c.close;x.volume+=c.volume;}}return[...map.values()].sort((a,b)=>new Date(a.time)-new Date(b.time));}
async function getTrend(symbol,interval){try{const b=getBroker();if(!b?.getHistoricalData)throw new Error('Active broker does not implement getHistoricalData()');if(interval==='FOUR_HOUR')return calculateTrend(symbol,interval,bucket4H(await b.getHistoricalData(symbol,'ONE_HOUR')));return calculateTrend(symbol,interval,await b.getHistoricalData(symbol,interval));}catch(e){console.log(`⚠️ ${symbol} ${interval} MTF failed: ${e.message}`);return emptyTrend('BROKER_DATA_ERROR');}}
async function getMultiTimeframeAnalysis(symbol){const[daily,fourHour,oneHour,fifteen]=await Promise.all([getTrend(symbol,'ONE_DAY'),getTrend(symbol,'FOUR_HOUR'),getTrend(symbol,'ONE_HOUR'),getTrend(symbol,'FIFTEEN_MINUTE')]);const t=[daily,fourHour,oneHour,fifteen],w=[30,30,20,20];let score=0;t.forEach((x,i)=>{if(x.bullish)score+=w[i];else if(x.bearish)score-=w[i];});const valid=t.filter(x=>x.valid),bull=valid.filter(x=>x.bullish).length,bear=valid.filter(x=>x.bearish).length,alignment=Math.max(bull,bear);let overall='SIDEWAYS';if(score>=70)overall='STRONG BULLISH';else if(score>=40)overall='BULLISH';else if(score<=-70)overall='STRONG BEARISH';else if(score<=-40)overall='BEARISH';let label='MIXED';if(valid.length===4&&bull===4)label='FULL BULLISH';else if(valid.length===4&&bear===4)label='FULL BEARISH';else if(bull>=3&&bull>bear)label='BULLISH ALIGNED';else if(bear>=3&&bear>bull)label='BEARISH ALIGNED';else if(!bull&&!bear)label='UNKNOWN';return{dailyTrend:daily.direction,fourHourTrend:fourHour.direction,oneHourTrend:oneHour.direction,fifteenMinTrend:fifteen.direction,dailyTrendLabel:daily.trend,fourHourTrendLabel:fourHour.trend,oneHourTrendLabel:oneHour.trend,fifteenMinTrendLabel:fifteen.trend,mtfScore:score,bullishTimeframes:bull,bearishTimeframes:bear,unknownTimeframes:t.length-valid.length,validTimeframes:valid.length,directionBias:bull>bear?'BULLISH':bear>bull?'BEARISH':'NEUTRAL',overallTrend:overall,alignment:label,mtfAlignment:alignment,alignedTimeframes:alignment,details:{daily,fourHour,oneHour,fifteen}};}
module.exports={getMultiTimeframeAnalysis,getTrend,bucket4H};
