const { getBroker } = require('./brokers');
const { calculateIndicators } = require('./indicators');
const TIMEFRAMES=Object.freeze([{key:'daily',interval:'ONE_DAY',weight:30,minCandles:220},{key:'fourHour',interval:'FOUR_HOUR',weight:25,minCandles:200},{key:'oneHour',interval:'ONE_HOUR',weight:25,minCandles:200},{key:'fifteenMin',interval:'FIFTEEN_MINUTE',weight:20,minCandles:200}]);
const num=v=>Number.isFinite(Number(v))?Number(v):null;
function emptyTrend(reason='NO_DATA',interval=''){return{trend:'UNKNOWN',direction:'UNKNOWN',bullish:false,bearish:false,score:0,bullishPoints:0,bearishPoints:0,valid:false,reason,interval,candles:0,indicatorQuality:{}};}
function normalize(candles){if(!Array.isArray(candles))return[];return candles.map(c=>({time:c?.time??c?.timestamp??c?.datetime??c?.date??c?.[0],open:num(c?.open??c?.[1]),high:num(c?.high??c?.[2]),low:num(c?.low??c?.[3]),close:num(c?.close??c?.[4]),volume:Math.max(0,num(c?.volume??c?.[5])??0)})).filter(c=>[c.open,c.high,c.low,c.close].every(Number.isFinite)&&c.open>0&&c.high>0&&c.low>0&&c.close>0&&c.high>=c.open&&c.high>=c.close&&c.low<=c.open&&c.low<=c.close).sort((a,b)=>new Date(a.time)-new Date(b.time));}
function direction(v){const s=String(v||'').toUpperCase();return s.includes('BULLISH')?'BULLISH':s.includes('BEARISH')?'BEARISH':'UNKNOWN';}
function calculateTrend(symbol,spec,candles){try{const data=normalize(candles);if(data.length<spec.minCandles)return emptyTrend(`INSUFFICIENT_CANDLES_${data.length}_OF_${spec.minCandles}`,spec.interval);const i=calculateIndicators(data),e20=num(i.ema20),e50=num(i.ema50),e200=num(i.ema200),rsi=num(i.rsi),m=i.macd||{},a=i.adx||{},macd=num(m.MACD??m.macd),signal=num(m.signal),adx=num(a.adx),pdi=num(a.pdi),mdi=num(a.mdi),last=data.at(-1)?.close;const quality={ema20:e20!==null,ema50:e50!==null,ema200:e200!==null,rsi:rsi!==null,macd:macd!==null&&signal!==null,adx:adx!==null,di:pdi!==null&&mdi!==null};const missing=Object.keys(quality).filter(k=>!quality[k]);if(missing.length)return emptyTrend(`MISSING_INDICATORS_${missing.join(',')}`,spec.interval);let bullishPoints=0,bearishPoints=0;if(e20>e50)bullishPoints++;else if(e20<e50)bearishPoints++;if(e50>e200)bullishPoints++;else if(e50<e200)bearishPoints++;if(last>e20)bullishPoints++;else if(last<e20)bearishPoints++;if(rsi>50)bullishPoints++;else if(rsi<50)bearishPoints++;if(macd>signal)bullishPoints++;else if(macd<signal)bearishPoints++;if(adx>=20){if(pdi>mdi)bullishPoints++;else if(mdi>pdi)bearishPoints++;}const bullish=bullishPoints>=3&&bullishPoints>bearishPoints,bearish=bearishPoints>=3&&bearishPoints>bullishPoints,trend=bullish?(bullishPoints>=4?'STRONG BULLISH':'BULLISH'):bearish?(bearishPoints>=4?'STRONG BEARISH':'BEARISH'):'SIDEWAYS';return{trend,direction:direction(trend),bullish,bearish,score:bullish?bullishPoints:bearish?-bearishPoints:0,bullishPoints,bearishPoints,valid:true,reason:'OK',interval:spec.interval,candles:data.length,indicatorQuality:quality};}catch(e){console.log(`⚠️ ${symbol} ${spec.interval} MTF failed: ${e.message}`);return emptyTrend('CALCULATION_ERROR',spec.interval);}}
async function getTrend(symbol,specOrInterval){const spec=typeof specOrInterval==='string'?TIMEFRAMES.find(x=>x.interval===specOrInterval):specOrInterval;if(!spec)return emptyTrend('UNSUPPORTED_TIMEFRAME',String(specOrInterval));try{const broker=getBroker();if(!broker?.getHistoricalData)throw new Error('Active broker does not implement getHistoricalData()');return calculateTrend(symbol,spec,await broker.getHistoricalData(symbol,spec.interval));}catch(e){console.log(`⚠️ ${symbol} ${spec.interval} MTF failed: ${e.message}`);return emptyTrend('BROKER_DATA_ERROR',spec.interval);}}
async function getMultiTimeframeAnalysis(symbol){const results=await Promise.all(TIMEFRAMES.map(spec=>getTrend(symbol,spec))),byKey=Object.fromEntries(results.map((r,i)=>[TIMEFRAMES[i].key,r])),valid=results.filter(r=>r.valid);let mtfScore=0;results.forEach((r,i)=>{if(r.bullish)mtfScore+=TIMEFRAMES[i].weight;else if(r.bearish)mtfScore-=TIMEFRAMES[i].weight;});const bull=valid.filter(r=>r.bullish).length,bear=valid.filter(r=>r.bearish).length,alignment=Math.max(bull,bear);let overallTrend='SIDEWAYS';if(mtfScore>=70)overallTrend='STRONG BULLISH';else if(mtfScore>=40)overallTrend='BULLISH';else if(mtfScore<=-70)overallTrend='STRONG BEARISH';else if(mtfScore<=-40)overallTrend='BEARISH';let label='MIXED';if(valid.length===4&&bull===4)label='FULL BULLISH';else if(valid.length===4&&bear===4)label='FULL BEARISH';else if(bull>=3&&bull>bear)label='BULLISH ALIGNED';else if(bear>=3&&bear>bull)label='BEARISH ALIGNED';else if(!bull&&!bear)label='UNKNOWN';return{dailyTrend:byKey.daily.direction,fourHourTrend:byKey.fourHour.direction,oneHourTrend:byKey.oneHour.direction,fifteenMinTrend:byKey.fifteenMin.direction,dailyTrendLabel:byKey.daily.trend,fourHourTrendLabel:byKey.fourHour.trend,oneHourTrendLabel:byKey.oneHour.trend,fifteenMinTrendLabel:byKey.fifteenMin.trend,mtfScore,bullishTimeframes:bull,bearishTimeframes:bear,unknownTimeframes:results.length-valid.length,validTimeframes:valid.length,directionBias:bull>bear?'BULLISH':bear>bull?'BEARISH':'NEUTRAL',overallTrend,alignment:label,mtfAlignment:alignment,alignedTimeframes:alignment,details:{daily:byKey.daily,fourHour:byKey.fourHour,oneHour:byKey.oneHour,fifteenMin:byKey.fifteenMin}};}
module.exports={getMultiTimeframeAnalysis,getTrend,TIMEFRAMES};