// Canonical 100-stock option scanning universe.
// This is the single source of truth for the option branch.
// Runtime option scanning starts here; it does not rebuild the universe from WHOLE_NSE.
const OPTION_UNIVERSE_100 = Object.freeze([
  "RELIANCE","HDFCBANK","ICICIBANK","SBIN","AXISBANK","KOTAKBANK","BHARTIARTL","TCS","INFY","HCLTECH",
  "WIPRO","LT","M&M","MARUTI","TATAMOTORS","SUNPHARMA","ADANIENT","ADANIPORTS","TATASTEEL","HINDALCO",
  "JSWSTEEL","BAJFINANCE","BAJAJFINSV","SHRIRAMFIN","INDUSINDBK","BANKBARODA","PNB","CANBK","NTPC","POWERGRID",
  "ONGC","BPCL","BEL","HAL","TATAPOWER","TATACONSUM","TITAN","TRENT","ULTRACEMCO","EICHERMOT",
  "TECHM","LTIM","COFORGE","PERSISTENT","MARICO","HINDUNILVR","ITC","NESTLEIND","ASIANPAINT","TATACHEM",
  "CIPLA","DRREDDY","DIVISLAB","LUPIN","TORNTPHARM","APOLLOHOSP","MUTHOOTFIN","MANAPPURAM","PFC","RECLTD",
  "REC","SAIL","COALINDIA","VEDL","NMDC","NATIONALUM","GAIL","IOC","HINDPETRO","IGL",
  "TVSMOTOR","BAJAJ-AUTO","HEROMOTOCO","ASHOKLEY","DLF","ABB","SIEMENS","BHEL","CUMMINSIND","POLYCAB",
  "DIXON","BHARATFORG","EXIDEIND","MOTHERSON","AARTIIND","BIOCON","AUROPHARMA","GLENMARK","LAURUSLABS","GRANULES",
  "JINDALSTEL","MGL","INDUSTOWER","IRCTC","INDIGO","IEX","CHOLAFIN","FEDERALBNK","RBLBANK","PVRINOX"
]);

function getOptionUniverseSymbols() {
  return [...OPTION_UNIVERSE_100];
}

module.exports = { OPTION_UNIVERSE_100, getOptionUniverseSymbols };
