const axios=require("axios");
const config=require("./config");
const TIMEOUT=120000,EQUITY_MAX_ROWS=20,OPTIONS_MAX_ROWS=20;
const EQUITY_COLUMNS=["rank","horizon","stock","symbol","price","buyZone","entry","stopLoss","target1","target2","holdingPeriod","rsi","support","resistance","volumeConfirmed","breakout","setupQuality","recommendation","reason","timestamp","chartPattern","patternStatus","patternDirection","patternTimeframe","patternConfidence","patternScore","patternContribution","patternBreakoutLevel","patternInvalidationLevel","patternTarget","patternDescription","patternDetectedAt"];
const OPTION_COLUMNS=["rank","stock","symbol","optionType","optionName","optionSymbol","optionExpiry","recommendedStrike","optionStrike","price","entry","stopLoss","target1","target2","riskReward","optionsDecision","optionsRating","optionsConfidence","optionsReason","tradeGates","failedGates","failedGateCount","contractAvailable","optionPriceAvailable","optionSetupAvailable","dailyTrend","fourHourTrend","oneHourTrend","fifteenMinTrend","mtfScore","mtfAlignment","breakout","oiMood","oiSentiment","callOI","putOI","pcr","optionEntry","optionLTP","optionStopLoss","optionTarget1","optionTarget2","optionRisk","optionReward","optionRiskReward","optionInstrumentKey","optionSide","timestamp"];
function webhook(){return process.env.GOOGLE_SHEET_WEBHOOK_URL||process.env.GOOGLE_SCRIPT_URL||process.env.GOOGLE_SHEETS_WEBHOOK_URL||process.env.GOOGLE_SHEET_URL||process.env.GOOGLE_APPS_SCRIPT_URL||config.GOOGLE_SHEET_WEBHOOK_URL||config.GOOGLE_SCRIPT_URL||config.GOOGLE_SHEETS_WEBHOOK_URL||config.GOOGLE_SHEET_URL||config.GOOGLE_APPS_SCRIPT_URL||null}
function clean(v){if(v==null)return"";if(typeof v==="number")return Number.isFinite(v)?v:"";if(typeof v==="boolean")return v;if(typeof v==="object"){try{return JSON.stringify(v)}catch(_){return String(v)}}return String(v)}
function n(r,ks,f=0){for(const k of ks){const v=Number(r?.[k]);if(Number.isFinite(v))return v}return f}
function s(r,ks,f=""){for(const k of ks)if(r?.[k]!=null&&String(r[k]).trim()!=="")return r[k];return f}
function yes(r,ks){return ks.some(k=>r?.[k]===true||String(r?.[k]??"").toLowerCase()==="true")}
function stock(r){return String(s(r,["stock","symbol","tradingSymbol","name"],"")).trim().toUpperCase()}
function price(r){return n(r,["price","ltp","lastPrice","currentPrice","close"])}
function support(r,i=1){const v=n(r,[`support${i}`]);return v>0?v:i===1?n(r,["support","s1"]):0}
function resistance(r,i=1){const v=n(r,[`resistance${i}`]);return v>0?v:i===1?n(r,["resistance","r1"]):0}
function direction(r){const d=String(s(r,["direction","stockDirection","technicalDirection","finalDirection","optionType"],"")).toUpperCase();if(["BULLISH","CALL","CE","LONG","BUY"].includes(d)||yes(r,["isBullish"]))return"BULLISH";if(["BEARISH","PUT","PE","SHORT","SELL"].includes(d)||yes(r,["isBearish"]))return"BEARISH";return"NEUTRAL"}
function trend(r,k){return String(r?.[k]??"").toUpperCase()}
function levels(r){const p=price(r),ss=[1,2,3].map(i=>support(r,i)).filter(v=>v>0&&v<p).sort((a,b)=>b-a),rr=[1,2,3].map(i=>resistance(r,i)).filter(v=>v>0&&v>p).sort((a,b)=>a-b);const rawSL=n(r,["stockStopLoss","stopLoss"]);return{p,sl:rawSL>0&&rawSL<p?rawSL:(ss[0]||0),s1:support(r,1),s2:support(r,2),s3:support(r,3),r1:resistance(r,1),r2:resistance(r,2),r3:resistance(r,3),supports:ss,resistances:rr}}
function validTradePlan(r){const d=direction(r),p=price(r),e=n(r,["entry","stockEntry","underlyingEntry","marketEntry"]),sl=n(r,["stockStopLoss","stopLoss"]),t1=n(r,["stockTarget1","target1"]),t2=n(r,["stockTarget2","target2"]),rr=n(r,["stockRiskReward","riskReward","rr"]);if(!["BULLISH","BEARISH"].includes(d)||p<=0||e<=0||sl<=0||t1<=0||rr<1.5)return false;if(Math.abs(e-sl)<e*0.0025)return false;if(d==="BULLISH"&&!(sl<e&&t1>e))return false;if(d==="BEARISH"&&!(sl>e&&t1<e))return false;if(t2>0&&(d==="BULLISH"?t2<t1:t2>t1))return false;return true}
function emaQuality(r){const p=price(r),e20=n(r,["ema20"]),e50=n(r,["ema50"]),e200=n(r,["ema200"]);return p>0&&(!e20||p>=e20)&&(!e50||p>=e50)&&(!e200||p>=e200)}
function patternFields(r){const b=r?.breakout&&typeof r.breakout==="object"?r.breakout:{};return{chartPattern:s(r,["chartPattern"],s(b,["chartPattern"],"NONE")),patternStatus:s(r,["patternStatus"],s(b,["patternStatus"],"NONE")),patternDirection:s(r,["patternDirection"],s(b,["patternDirection"],"NEUTRAL")),patternTimeframe:s(r,["patternTimeframe"],s(b,["patternTimeframe"],"1D")),patternConfidence:n(r,["patternConfidence"],n(b,["patternConfidence"])),patternScore:n(r,["patternScore"],n(b,["patternScore"])),patternContribution:n(r,["patternContribution"],n(b,["patternContribution"])),patternBreakoutLevel:n(r,["patternBreakoutLevel"],n(b,["patternBreakoutLevel"])),patternInvalidationLevel:n(r,["patternInvalidationLevel"],n(b,["patternInvalidationLevel"])),patternTarget:n(r,["patternTarget"],n(b,["patternTarget"])),patternDescription:s(r,["patternDescription"],s(b,["patternDescription"],"")),patternDetectedAt:s(r,["patternDetectedAt"],s(b,["patternDetectedAt"],""))}}
function rsiState(r,d){const x=n(r,["rsi"]);if(!x)return"UNKNOWN";if(d==="BULLISH")return x>=85?"EXTREME_OVERBOUGHT":x>=70?"OVERBOUGHT":x<=30?"OVERSOLD":"NORMAL";if(d==="BEARISH")return x<=15?"EXTREME_OVERSOLD":x<=30?"OVERSOLD":x>=70?"OVERBOUGHT":"NORMAL";return"NORMAL"}
function patternConflict(r,d){const p=String(r?.patternDirection??"").toUpperCase();return["BULLISH","BEARISH"].includes(p)&&p!==d}
function idea(r,h){const p=price(r),d=direction(r),e=n(r,["entry","stockEntry","underlyingEntry","marketEntry"]),sl=n(r,["stockStopLoss","stopLoss"]),t1=n(r,["stockTarget1","target1"]),t2=n(r,["stockTarget2","target2"]),pf=patternFields(r),vol=yes(r,["volumeConfirmed","volumeConfirmation","volumeConfirm"])||n(r,["volumeRatio5","rvol"])>=1.2,valid=validTradePlan(r),rs=rsiState(r,d),pc=patternConflict(r,d);return{horizon:h,stock:stock(r),symbol:s(r,["symbol","stock","tradingSymbol"],stock(r)),price:p,buyZone:valid&&d==="BULLISH"?String(sl)+" - "+String(e):"",entry:e,stopLoss:sl,target1:t1,target2:t2,holdingPeriod:h==="SHORT TERM"?"Days to few weeks":"Months to years",rsi:n(r,["rsi"]),support:support(r),resistance:resistance(r),volumeConfirmed:vol?"YES":"NO",breakout:clean(s(r,["breakoutType","breakout"],"NONE")),setupQuality:valid?(vol?"STRONG":"GOOD"):"INVALID",recommendation:valid?(d==="BULLISH"?"BUY":"SELL"):"WATCH",reason:valid?(pc?"Directional signal retained; chart pattern conflicts with it.":rs==="EXTREME_OVERBOUGHT"?"Directional signal retained; RSI is extremely overbought.":"Validated market-structure setup."):"No valid market-structure trade plan; excluded from trade-quality promotion.",timestamp:new Date().toISOString(),rsiState:rs,patternConflict:pc,...pf}}
function buildEquity(rows){const source=Array.isArray(rows)?rows.filter(r=>stock(r)&&price(r)>0):[],seen=new Set(),chosen=[];for(const r of source){const k=stock(r);if(seen.has(k))continue;seen.add(k);const d=direction(r),valid=validTradePlan(r),sc=Math.abs(n(r,["scannerScore","score","aiFinalScore","finalScore"]));if(valid)chosen.push({r,score:sc,priority:2});else if(d!=="NEUTRAL"&&sc>=5)chosen.push({r,score:sc,priority:1})}chosen.sort((a,b)=>(b.priority-a.priority)||(b.score-a.score));return chosen.slice(0,EQUITY_MAX_ROWS).map((x,i)=>({...idea(x.r,Math.abs(n(x.r,["scannerScore","score","aiFinalScore","finalScore"]))>=60?"SHORT TERM":"LONG TERM"),rank:i+1}))}
function optionType(r){const x=String(s(r,["optionType","optionsType","option_type","type","instrument_type","side","direction"],"")).toUpperCase();return x==="CALL"||x==="CE"||x.includes("CALL")?"CALL":x==="PUT"||x==="PE"||x.includes("PUT")?"PUT":""}
function optionSide(r){return optionType(r)==="CALL"?"CE":optionType(r)==="PUT"?"PE":""}
function optionName(r){return String(s(r,["optionName","optionSymbol","tradingsymbol","tradingSymbol","symbol"],"")).trim()}
function decision(r){return String(s(r,["optionsDecision","decision","optionDecision","tradeDecision"],"")).toUpperCase()}
function confidence(r){return n(r,["optionsConfidence","confidence","optionConfidence"])}
function riskReward(r){return n(r,["optionRiskReward","riskReward","rr","stockRiskReward"])}
function optionBuyCandidate(r){const t=optionType(r),d=decision(r);if(!t||!["TRADE","WATCH"].includes(d))return false;if(!(r?.optionInstrumentKey||r?.optionSymbol||r?.recommendedStrike||yes(r,["contractAvailable","hasContract","optionContractAvailable"])))return false;return n(r,["optionPremiumEntry","optionLTP","optionEntry","optionPrice","optionLastPrice"])>0}
function optionValue(r,c){const a={stock:["symbol","tradingSymbol"],symbol:["stock","tradingSymbol"],price:["ltp","lastPrice","currentPrice","close"],entry:["stockEntry"],stopLoss:["stockStopLoss"],target1:["stockTarget1"],target2:["stockTarget2"],riskReward:["rr","stockRiskReward"],optionType:["optionsType","option_type","type","side"],optionName:["optionSymbol","tradingsymbol","tradingSymbol","symbol"],optionSymbol:["tradingsymbol","tradingSymbol","option_symbol"],optionExpiry:["expiry","expiryDate"],recommendedStrike:["strike","strikePrice"],optionStrike:["strike","strikePrice","recommendedStrike"],optionsDecision:["decision","optionDecision","tradeDecision"],optionsRating:["rating","optionRating"],optionsConfidence:["confidence","optionConfidence"],optionsReason:["reason","optionReason"],failedGates:["failedGateList"],failedGateCount:["failedGatesCount"],contractAvailable:["hasContract","optionContractAvailable"],optionPriceAvailable:["hasOptionPrice","optionLtpAvailable"],optionSetupAvailable:["hasOptionSetup"],mtfAlignment:["mtfAligned","alignment"],optionEntry:["optionPremiumEntry","option_entry"],optionLTP:["optionPremiumEntry","option_ltp","optionLastPrice"],optionStopLoss:["optionPremiumStopLoss","option_stop_loss"],optionTarget1:["optionPremiumTarget1","option_target1","option_target_1"],optionTarget2:["optionPremiumTarget2","option_target2","option_target_2"],optionRisk:["optionPremiumRisk","option_risk"],optionReward:["optionPremiumReward","option_reward"],optionRiskReward:["optionPremiumRiskReward","option_rr"],optionInstrumentKey:["optionInstrumentKey","option_instrument_key"],optionSide:["optionSide"]};if(r?.[c]!=null&&r[c]!=="")return r[c];for(const k of a[c]||[])if(r?.[k]!=null&&r[k]!=="")return r[k];if(c==="optionSide")return optionSide(r);if(c==="optionName")return optionName(r);return""}
function optionRows(rows){const seen=new Set(),out=[];for(const r of rows||[]){if(!optionBuyCandidate(r))continue;const k=`${stock(r)}|${optionType(r)}|${String(optionValue(r,"optionSymbol")).toUpperCase()}`;if(!seen.has(k)){seen.add(k);out.push(r)}}return out.sort((a,b)=>confidence(b)-confidence(a)||riskReward(b)-riskReward(a)).slice(0,OPTIONS_MAX_ROWS)}
async function postSheet(sheet,headers,rows){const url=webhook();if(!url)throw new Error("Google Sheet webhook URL is missing.");const res=await axios.post(url,{action:"replaceSheet",sheet,clearFirst:true,headers,rows,timestamp:new Date().toISOString()},{timeout:TIMEOUT,headers:{"Content-Type":"application/json"}});if(res?.data?.success!==true)throw new Error(`Google Sheets rejected ${sheet}: ${res?.data?.error||"invalid success response"}`);if(String(res?.data?.sheet||"")!==sheet)throw new Error(`Google Sheets response sheet mismatch: expected ${sheet}, received ${res?.data?.sheet||""}`);if(Number(res?.data?.rowCount||0)!==rows.length)throw new Error(`Google Sheets row-count mismatch for ${sheet}: sent ${rows.length}, received ${res?.data?.rowCount}`);return res.data}
async function updateStrategySheets(scannerData,optionDecisions,equityData=scannerData){const scanner=Array.isArray(scannerData)?scannerData.filter(Boolean):[],source=Array.isArray(equityData)?equityData.filter(Boolean):scanner,options=Array.isArray(optionDecisions)?optionDecisions.filter(Boolean):[],equity=buildEquity(source),equityRows=equity.map(r=>EQUITY_COLUMNS.map(c=>clean(r[c]))),unique=optionRows(options),calls=unique.filter(r=>optionType(r)==="CALL"),puts=unique.filter(r=>optionType(r)==="PUT"),callRows=calls.map((r,i)=>OPTION_COLUMNS.map(c=>c==="rank"?i+1:clean(optionValue(r,c)))),putRows=puts.map((r,i)=>OPTION_COLUMNS.map(c=>c==="rank"?i+1:clean(optionValue(r,c))));const equityResult=await postSheet("EQUITY",EQUITY_COLUMNS,equityRows),callResult=await postSheet("CALL_OPTIONS",OPTION_COLUMNS,callRows),putResult=await postSheet("PUT_OPTIONS",OPTION_COLUMNS,putRows);return{success:true,scannerRows:scanner.length,equityRows:equityRows.length,callRows:callRows.length,putRows:putRows.length,equity:equityResult,calls:callResult,puts:putResult}}
module.exports={EQUITY_COLUMNS,OPTION_COLUMNS,updateStrategySheets};