// ============================================================
// TRADE SETUP — MARKET STRUCTURE + VOLATILITY PROJECTION
// ============================================================
function positiveNumber(v){const n=Number(v);return Number.isFinite(n)&&n>0?n:0;}
function round(v){const n=positiveNumber(v);return n?Number(n.toFixed(2)):0;}
function getDirection(stock={},option={}){const raw=String(option.optionType??stock.optionType??stock.direction??stock.finalDirection??stock.stockDirection??'').trim().toUpperCase();if(['CALL','CE','BULLISH','BUY'].includes(raw))return'CALL';if(['PUT','PE','BEARISH','SELL'].includes(raw))return'PUT';return null;}
function collectLevels(stock={},entry){const sv=[...(Array.isArray(stock.supportLevels)?stock.supportLevels:[]),stock.support,stock.support1,stock.support2,stock.support3,stock.s1,stock.s2,stock.s3,stock.pivotS1,stock.pivotS2,stock.pivotS3,stock.oiSupport1,stock.oiSupport2,stock.oiSupport3,stock.swingLow,stock.previousLow,stock.recentLow,stock.dayLow];const rv=[...(Array.isArray(stock.resistanceLevels)?stock.resistanceLevels:[]),stock.resistance,stock.resistance1,stock.resistance2,stock.resistance3,stock.r1,stock.r2,stock.r3,stock.pivotR1,stock.pivotR2,stock.pivotR3,stock.oiResistance1,stock.oiResistance2,stock.oiResistance3,stock.swingHigh,stock.previousHigh,stock.recentHigh,stock.dayHigh];return{supports:[...new Set(sv.map(positiveNumber).filter(v=>v>0&&v<entry))].sort((a,b)=>b-a),resistances:[...new Set(rv.map(positiveNumber).filter(v=>v>entry))].sort((a,b)=>a-b)};}
function riskReward(e,s,t,d){e=Number(e);s=Number(s);t=Number(t);if(![e,s,t].every(Number.isFinite)||e<=0||s<=0||t<=0)return 0;const risk=d==='CALL'?e-s:s-e,reward=d==='CALL'?t-e:e-t;return risk>0&&reward>0?Number((reward/risk).toFixed(2)):0;}
function technicalConfidence(stock={},direction,rr){const entry=positiveNumber(stock.price??stock.close??stock.entry);if(!entry)return 0;const e5=positiveNumber(stock.ema5),e9=positiveNumber(stock.ema9),e20=positiveNumber(stock.ema20),e50=positiveNumber(stock.ema50),rsi=Number(stock.rsi),macd=Number(stock.macdValue??stock.macd),signal=Number(stock.macdSignal),adx=Number(stock.adx),pdi=Number(stock.pdi),mdi=Number(stock.mdi),vwap=positiveNumber(stock.vwap),rvol=Number(stock.rvol);let score=50,bull=direction==='CALL';if([e5,e9,e20,e50].every(Boolean)&&((bull&&e5>e9&&e9>e20&&e20>e50)||(!bull&&e5<e9&&e9<e20&&e20<e50)))score+=12;if(e20&&e50&&((bull&&entry>e20&&entry>e50)||(!bull&&entry<e20&&entry<e50)))score+=8;if(Number.isFinite(rsi)&&((bull&&rsi>=55&&rsi<=70)||(!bull&&rsi>=30&&rsi<=45)))score+=7;if(Number.isFinite(macd)&&Number.isFinite(signal)&&((bull&&macd>=signal)||(!bull&&macd<=signal)))score+=7;if(Number.isFinite(adx)&&adx>=20&&((bull&&pdi>mdi)||(!bull&&mdi>pdi)))score+=7;if(vwap&&((bull&&entry>vwap)||(!bull&&entry<vwap)))score+=4;if(Number.isFinite(rvol))score+=rvol>=2?5:rvol>=1.2?3:0;if(rr>=2)score+=3;else if(rr>=1.5)score+=2;return Math.max(0,Math.min(100,Math.round(score)));}
module.exports=function calculateTradeSetup(stock={},option={}){const direction=getDirection(stock,option),entry=positiveNumber(option.entry??stock.marketEntry??stock.entry??stock.stockEntry??stock.price??stock.ltp??stock.close),{supports,resistances}=collectLevels(stock,entry),base={valid:false,isValid:false,direction,optionType:direction,entry:round(entry),stockEntry:round(entry),stopLoss:0,sl:0,target1:0,t1:0,target2:0,t2:0,risk:0,reward:0,riskReward:0,rr:0,confidence:0,stopSource:'MARKET_STRUCTURE_REQUIRED',target1Source:'MARKET_STRUCTURE_REQUIRED',target2Source:'MARKET_STRUCTURE_OPTIONAL',targetSource:'MARKET_STRUCTURE_REQUIRED',levelsSource:'MARKET_STRUCTURE',supportLevels:supports,resistanceLevels:resistances,reason:'UNKNOWN'};if(!direction)return{...base,direction:null,optionType:null,reason:'NO_DIRECTION'};if(!entry)return{...base,reason:'NO_MARKET_ENTRY'};const minRisk=Math.max(entry*0.0025,0.01),stopCandidates=direction==='CALL'?supports:resistances,stop=stopCandidates.find(level=>(direction==='CALL'?entry-level:level-entry)>=minRisk)||0,candidates=direction==='CALL'?resistances:supports;if(!stop)return{...base,confidence:technicalConfidence(stock,direction,0),reason:direction==='CALL'?'MISSING_MARKET_SUPPORT':'MISSING_MARKET_RESISTANCE'};const risk=direction==='CALL'?entry-stop:stop-entry;if(!(risk>0))return{...base,confidence:technicalConfidence(stock,direction,0),reason:'INVALID_MARKET_RISK'};if(risk<minRisk)return{...base,stopLoss:round(stop),sl:round(stop),risk:round(risk),confidence:technicalConfidence(stock,direction,0),reason:'STOP_TOO_TIGHT_FOR_REALISTIC_TRADE'};const validTargets=candidates.filter(t=>riskReward(entry,stop,t,direction)>=1.5);
const atr=positiveNumber(stock.atr??stock.ATR);
const patternTarget=positiveNumber(stock.patternTarget);
const projected1=direction==='CALL'?entry+Math.max(risk*1.5,atr>0?atr*1.5:0):entry-Math.max(risk*1.5,atr>0?atr*1.5:0);
const projected2=direction==='CALL'?entry+Math.max(risk*2,atr>0?atr*2:0):entry-Math.max(risk*2,atr>0?atr*2:0);
let target1=validTargets[0]||0,target2=validTargets[1]||0,target1Source=target1?'MARKET_STRUCTURE':'',target2Source=target2?'NEXT_MARKET_STRUCTURE':'',targetSource=target1?'MARKET_STRUCTURE':'';
if(!target1&&patternTarget>0&&((direction==='CALL'&&patternTarget>entry)||(direction==='PUT'&&patternTarget<entry))&&riskReward(entry,stop,patternTarget,direction)>=1.5){target1=patternTarget;target1Source='PATTERN_TARGET';targetSource='PATTERN_TARGET';}
if(!target1&&projected1>0&&riskReward(entry,stop,projected1,direction)>=1.5){target1=projected1;target1Source='ATR_RR_FALLBACK';targetSource='ATR_RR_FALLBACK';}
if(!target1)return{...base,stopLoss:round(stop),sl:round(stop),risk:round(risk),confidence:technicalConfidence(stock,direction,0),stopSource:direction==='CALL'?'MARKET_SUPPORT':'MARKET_RESISTANCE',reason:'MISSING_TARGET_WITHOUT_VALID_STRUCTURE'}; 
if(!target2){if(patternTarget>0&&((direction==='CALL'&&patternTarget>target1)||(direction==='PUT'&&patternTarget<target1))&&riskReward(entry,stop,patternTarget,direction)>riskReward(entry,stop,target1,direction)){target2=patternTarget;target2Source='PATTERN_TARGET';}else if(projected2>0&&riskReward(entry,stop,projected2,direction)>riskReward(entry,stop,target1,direction)){target2=projected2;target2Source='ATR_RR_FALLBACK';}else{target2=direction==='CALL'?entry+risk*2:entry-risk*2;target2Source='RR_2R_FALLBACK';}}
const reward=direction==='CALL'?target1-entry:entry-target1,rr=riskReward(entry,stop,target1,direction);if(!(rr>=1.5))return{...base,stopLoss:round(stop),sl:round(stop),target1:round(target1),t1:round(target1),risk:round(risk),reward:round(Math.max(0,reward)),riskReward:rr,rr,confidence:technicalConfidence(stock,direction,rr),stopSource:direction==='CALL'?'MARKET_SUPPORT':'MARKET_RESISTANCE',target1Source,targetSource,reason:'NO_TARGET_WITH_MIN_RR_1_5'};return{...base,valid:true,isValid:true,stopLoss:round(stop),sl:round(stop),target1:round(target1),t1:round(target1),target2:round(target2),t2:round(target2),risk:round(risk),reward:round(reward),riskReward:rr,rr,confidence:technicalConfidence(stock,direction,rr),stopSource:direction==='CALL'?'MARKET_SUPPORT':'MARKET_RESISTANCE',target1Source,target2Source,targetSource,levelsSource:'MARKET_STRUCTURE',reason:'VALID_MARKET_STRUCTURE_RR'};};
module.exports.calculateTradeSetup=module.exports;module.exports.getDirection=getDirection;module.exports.riskReward=riskReward;
