module.exports = function calculateTradeSetup(stock = {}, option = {}) {
  const n = v => Number.isFinite(Number(v)) && Number(v) > 0 ? Number(v) : 0;
  const round = v => n(v) ? Number(n(v).toFixed(2)) : 0;
  const direction = String(option.optionType || stock.optionType || stock.direction || stock.finalDirection || stock.stockDirection || '').toUpperCase();
  const type = direction === 'CALL' || direction === 'CE' || direction === 'BULLISH' || direction === 'BUY' ? 'CALL' : direction === 'PUT' || direction === 'PE' || direction === 'BEARISH' || direction === 'SELL' ? 'PUT' : null;
  const entry = n(option.entry ?? stock.marketEntry ?? stock.entry ?? stock.stockEntry ?? stock.price ?? stock.ltp ?? stock.close);
  const supports = [...new Set([...(Array.isArray(stock.supportLevels) ? stock.supportLevels : []), stock.support1, stock.support2, stock.support3, stock.pivotS1, stock.pivotS2, stock.pivotS3, stock.oiSupport1, stock.oiSupport2, stock.oiSupport3].map(n).filter(v => v > 0))].filter(v => v < entry).sort((a,b)=>b-a);
  const resistances = [...new Set([...(Array.isArray(stock.resistanceLevels) ? stock.resistanceLevels : []), stock.resistance1, stock.resistance2, stock.resistance3, stock.pivotR1, stock.pivotR2, stock.pivotR3, stock.oiResistance1, stock.oiResistance2, stock.oiResistance3].map(n).filter(v => v > 0))].filter(v => v > entry).sort((a,b)=>a-b);
  if (!type) return { valid:false,isValid:false,direction:null,optionType:null,entry:round(entry),stockEntry:round(entry),stopLoss:0,target1:0,target2:0,risk:0,reward:0,riskReward:0,rr:0,supportLevels:supports,resistanceLevels:resistances,levelsSource:'MARKET_STRUCTURE_ONLY',reason:'NO_DIRECTION' };
  if (!entry) return { valid:false,isValid:false,direction:type,optionType:type,entry:0,stockEntry:0,stopLoss:0,target1:0,target2:0,risk:0,reward:0,riskReward:0,rr:0,supportLevels:supports,resistanceLevels:resistances,levelsSource:'MARKET_STRUCTURE_ONLY',reason:'NO_MARKET_ENTRY' };
  const stop = type === 'CALL' ? supports[0] || 0 : resistances[0] || 0;
  const candidates = type === 'CALL' ? resistances : supports;
  const rrFor = target => { const risk = type === 'CALL' ? entry-stop : stop-entry; const reward = type === 'CALL' ? target-entry : entry-target; return risk > 0 && reward > 0 ? reward/risk : 0; };
  const idx = candidates.findIndex(v => rrFor(v) >= 1.5);
  const target1 = idx >= 0 ? candidates[idx] : (candidates[0] || 0);
  const target2 = idx >= 0 ? (candidates[idx+1] || 0) : (candidates[1] || 0);
  const risk = type === 'CALL' ? entry-stop : stop-entry;
  const reward = type === 'CALL' ? target1-entry : entry-target1;
  const rr = risk > 0 && reward > 0 ? Number((reward/risk).toFixed(2)) : 0;
  const valid = !!stop && !!target1 && rr >= 1.5;
  const reason = !stop || !target1 ? 'MISSING_MARKET_STRUCTURE_LEVEL' : valid ? 'VALID_MARKET_STRUCTURE_RR' : 'LOW_MARKET_RR';
  return { valid,isValid:valid,direction:type,optionType:type,entry:round(entry),stockEntry:round(entry),stopLoss:round(stop),sl:round(stop),target1:round(target1),t1:round(target1),target2:round(target2),t2:round(target2),risk:round(risk),reward:round(reward),riskReward:rr,rr,stopSource:stop ? (type==='CALL'?'MARKET_SUPPORT':'MARKET_RESISTANCE'):'MARKET_STRUCTURE_REQUIRED',target1Source:target1?'MARKET_STRUCTURE':'MARKET_STRUCTURE_REQUIRED',target2Source:target2?'NEXT_MARKET_STRUCTURE':'MARKET_STRUCTURE_OPTIONAL',targetSource:target1?'MARKET_STRUCTURE':'MARKET_STRUCTURE_REQUIRED',levelsSource:'MARKET_STRUCTURE_ONLY',supportLevels:supports,resistanceLevels:resistances,reason };
};
module.exports.calculateTradeSetup = module.exports;
module.exports.getDirection = (stock={},option={}) => { const x=String(option.optionType||stock.optionType||stock.direction||stock.finalDirection||stock.stockDirection||'').toUpperCase(); return ['CALL','CE','BULLISH','BUY'].includes(x)?'CALL':['PUT','PE','BEARISH','SELL'].includes(x)?'PUT':null; };
module.exports.riskReward = (entry,stop,target,direction) => { const e=Number(entry),s=Number(stop),t=Number(target); const r=direction==='CALL'?e-s:s-e, w=direction==='CALL'?t-e:e-t; return r>0&&w>0?Number((w/r).toFixed(2)):0; };